# Macroeconomic forecasting: Can machine learning methods outperform traditional approaches?

## 0. Setup of the notebook


### Loading packages and modules

In [1]:
import os
import numpy as np
import pandas as pd
pd.set_option('display.max_rows', 250)

# models
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVR
from sklearn.tree import DecisionTreeRegressor
from sklearn.linear_model import Lasso
from sklearn.ensemble import GradientBoostingRegressor 

from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split
from sklearn import preprocessing

from sklearn.model_selection import GridSearchCV

from pmdarima.arima import auto_arima

# pytorch
from torch import nn, no_grad, save, load
from torch import from_numpy, zeros
from torch.optim import SGD, Adam
from torch.utils.data import DataLoader, TensorDataset

import torch as T
import torch.nn as nn
import torch.nn.functional as F

# plots
import matplotlib.pyplot as plt
plt.style.use('seaborn-dark')

import seaborn as sns
sns.set_style("darkgrid")

import pickle

C:\Users\hauer\anaconda3\envs\test\lib\site-packages\sklearn\externals\six.py:31: FutureWarning: The module is deprecated in version 0.21 and will be removed in version 0.23 since we've dropped support for Python 2.7. Please rely on the official version of six (https://pypi.org/project/six/).
  "(https://pypi.org/project/six/).", FutureWarning)
C:\Users\hauer\anaconda3\envs\test\lib\site-packages\sklearn\externals\joblib\__init__.py:15: FutureWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=FutureWarning)

# 1. Data

## 1.1 Real gross domestic product 

The gross domestic product (GDP) is the variable of interest.

Source of the data public availabe on the website of the IMF [here](https://www.imf.org/en/Publications/WEO/weo-database/2020/October/download-entire-database) and provided via an Excel file called `WEOApr2020all.xls`.

In [2]:
file = r"C:\Users\hauer\Dropbox\CFDS\Project\data2\WEOApr2020all.csv"
df_weo_real_gdp = pd.read_csv(file)

There are several types of data in this file. This is the description of the relevant subject, the growth of the GDP:

In [3]:
idx = df_weo_real_gdp['Subject Descriptor'] == 'Gross domestic product, constant prices'
df_weo_real_gdp['Subject Notes'] 

df_weo_real_gdp.loc[idx, 'Subject Notes'].unique()

array(['Annual percentages of constant price GDP are year-on-year changes; the base year is country-specific . Expenditure-based GDP is total final expenditures at purchasers? prices (including the f.o.b. value of exports of goods and services), less the f.o.b. value of imports of goods and services. [SNA 1993]'],
      dtype=object)

In [4]:
df_weo_real_gdp.loc[idx, 'Units'].unique()

array(['Percent change'], dtype=object)

The subject code given by the IMF is 'NGDP_RPCH'. This code will also occour in for the weo prediction data.

In [5]:
df_weo_real_gdp.loc[idx, 'WEO Subject Code'].unique()

array(['NGDP_RPCH'], dtype=object)

As the data for the years are present in the columns of the dataframe, i exctract the relevant information and transpose it afterwars. I want the years as the rows and the variables as the columns.

In [6]:
df_weo_real_gdp.columns

Index(['WEO Country Code', 'ISO', 'WEO Subject Code', 'Country',
       'Subject Descriptor', 'Subject Notes', 'Units', 'Scale',
       'Country/Series-specific Notes', '1980', '1981', '1982', '1983', '1984',
       '1985', '1986', '1987', '1988', '1989', '1990', '1991', '1992', '1993',
       '1994', '1995', '1996', '1997', '1998', '1999', '2000', '2001', '2002',
       '2003', '2004', '2005', '2006', '2007', '2008', '2009', '2010', '2011',
       '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019', '2020',
       '2021', 'Estimates Start After'],
      dtype='object')

This is done with the function:

In [7]:
def get_imf_woe_data(df_weo_real_gdp, country, remove_na=False):

    df = df_weo_real_gdp[df_weo_real_gdp['Country'] == country]
    
    result = pd.DataFrame()
    
    available_variables = df['Subject Descriptor'].unique()
    
    for variable in available_variables:
        df_curr = df[df['Subject Descriptor'] == variable]
        df_curr = df_curr.iloc[:, 9:49]
        df_curr = df_curr.transpose()
        df_curr = df_curr.rename({df_curr.columns[0]: variable}, axis='columns')
        result = pd.concat([result, df_curr], axis=1)
        
        
    if remove_na:
        result = result.dropna(axis=1) 
        
    return result

To extract the GDP data i use this function:

In [8]:
def get_gdp_real(df_weo_real_gdp, country):
    df = get_imf_woe_data(df_weo_real_gdp, country, remove_na=False)
    df.index = df.index.astype(dtype='int64')   
    df['GDP real'] = df['Gross domestic product, constant prices']  
    df['GDP real'] = df['GDP real'].str.replace(',', '').astype('float')
    return df['GDP real']

Here is for example the real GDP growth for germany:

In [9]:
get_gdp_real(df_weo_real_gdp, 'Germany')

1980    1.272
1981    0.110
1982   -0.788
1983    1.555
1984    2.826
1985    2.192
1986    2.417
1987    1.469
1988    3.736
1989    3.913
1990    5.723
1991    5.011
1992    1.925
1993   -0.976
1994    2.395
1995    1.541
1996    0.814
1997    1.790
1998    2.019
1999    1.885
2000    2.905
2001    1.689
2002   -0.201
2003   -0.708
2004    1.186
2005    0.728
2006    3.815
2007    2.975
2008    0.965
2009   -5.694
2010    4.185
2011    3.913
2012    0.428
2013    0.431
2014    2.218
2015    1.742
2016    2.230
2017    2.465
2018    1.522
2019    0.565
Name: GDP real, dtype: float64

The real GDP is availabe for the following 194 (one occurrence is Nan) countries:

In [10]:
countries_woe_real = df_weo_real_gdp['Country'].unique()
len(countries_woe_real)

195

In [11]:
countries_woe_real

array(['Afghanistan', 'Albania', 'Algeria', 'Angola',
       'Antigua and Barbuda', 'Argentina', 'Armenia', 'Aruba',
       'Australia', 'Austria', 'Azerbaijan', 'The Bahamas', 'Bahrain',
       'Bangladesh', 'Barbados', 'Belarus', 'Belgium', 'Belize', 'Benin',
       'Bhutan', 'Bolivia', 'Bosnia and Herzegovina', 'Botswana',
       'Brazil', 'Brunei Darussalam', 'Bulgaria', 'Burkina Faso',
       'Burundi', 'Cabo Verde', 'Cambodia', 'Cameroon', 'Canada',
       'Central African Republic', 'Chad', 'Chile', 'China', 'Colombia',
       'Comoros', 'Democratic Republic of the Congo', 'Republic of Congo',
       'Costa Rica', "Côte d'Ivoire", 'Croatia', 'Cyprus',
       'Czech Republic', 'Denmark', 'Djibouti', 'Dominica',
       'Dominican Republic', 'Ecuador', 'Egypt', 'El Salvador',
       'Equatorial Guinea', 'Eritrea', 'Estonia', 'Eswatini', 'Ethiopia',
       'Fiji', 'Finland', 'France', 'Gabon', 'The Gambia', 'Georgia',
       'Germany', 'Ghana', 'Greece', 'Grenada', 'Guatemala', 'Guinea',
       'Guinea-Bissau', 'Guyana', 'Haiti', 'Honduras', 'Hong Kong SAR',
       'Hungary', 'Iceland', 'India', 'Indonesia',
       'Islamic Republic of Iran', 'Iraq', 'Ireland', 'Israel', 'Italy',
       'Jamaica', 'Japan', 'Jordan', 'Kazakhstan', 'Kenya', 'Kiribati',
       'Korea', 'Kosovo', 'Kuwait', 'Kyrgyz Republic', 'Lao P.D.R.',
       'Latvia', 'Lebanon', 'Lesotho', 'Liberia', 'Libya', 'Lithuania',
       'Luxembourg', 'Macao SAR', 'Madagascar', 'Malawi', 'Malaysia',
       'Maldives', 'Mali', 'Malta', 'Marshall Islands', 'Mauritania',
       'Mauritius', 'Mexico', 'Micronesia', 'Moldova', 'Mongolia',
       'Montenegro', 'Morocco', 'Mozambique', 'Myanmar', 'Namibia',
       'Nauru', 'Nepal', 'Netherlands', 'New Zealand', 'Nicaragua',
       'Niger', 'Nigeria', 'North Macedonia', 'Norway', 'Oman',
       'Pakistan', 'Palau', 'Panama', 'Papua New Guinea', 'Paraguay',
       'Peru', 'Philippines', 'Poland', 'Portugal', 'Puerto Rico',
       'Qatar', 'Romania', 'Russia', 'Rwanda', 'Samoa', 'San Marino',
       'São Tomé and Príncipe', 'Saudi Arabia', 'Senegal', 'Serbia',
       'Seychelles', 'Sierra Leone', 'Singapore', 'Slovak Republic',
       'Slovenia', 'Solomon Islands', 'Somalia', 'South Africa',
       'South Sudan', 'Spain', 'Sri Lanka', 'St. Kitts and Nevis',
       'St. Lucia', 'St. Vincent and the Grenadines', 'Sudan', 'Suriname',
       'Sweden', 'Switzerland', 'Syria', 'Taiwan Province of China',
       'Tajikistan', 'Tanzania', 'Thailand', 'Timor-Leste', 'Togo',
       'Tonga', 'Trinidad and Tobago', 'Tunisia', 'Turkey',
       'Turkmenistan', 'Tuvalu', 'Uganda', 'Ukraine',
       'United Arab Emirates', 'United Kingdom', 'United States',
       'Uruguay', 'Uzbekistan', 'Vanuatu', 'Venezuela', 'Vietnam',
       'Yemen', 'Zambia', 'Zimbabwe', nan], dtype=object)

## 1.2 The variables X

### 1.2.1 IMF

The IMF proivdes some economic variables along with the realised GDP, that are already in the `df_weo_real_gdp` dataframe:

In [12]:
df_imf_woe_data =  get_imf_woe_data(df_weo_real_gdp, 'Germany', remove_na=False)
df_imf_woe_data.head()

,"Gross domestic product, constant prices","Gross domestic product, current prices","Gross domestic product per capita, constant prices","Inflation, average consumer prices","Inflation, end of period consumer prices",Unemployment rate,General government net lending/borrowing,Current account balance
1980,1.272,867.363,0.931,5.447,NaN,3.359,NaN,-1.782
1981,0.11,950.471,-0.078,6.324,NaN,4.831,NaN,-0.684
1982,-0.788,"1,001.24",-0.717,5.256,NaN,6.734,NaN,0.866
1983,1.555,"1,056.63",1.91,3.284,NaN,8.099,NaN,0.666
1984,2.826,"1,125.70",3.243,2.396,NaN,8.058,NaN,1.423

I will use the following quantities:

In [13]:
imf_woe_variables = ['Inflation, average consumer prices', 'Unemployment rate', 'General government net lending/borrowing', 'Current account balance']

for x in imf_woe_variables:
    idx = df_weo_real_gdp['Subject Descriptor'] == x
    print(x)
    print(df_weo_real_gdp.loc[idx, 'Subject Notes'].unique())
    print(df_weo_real_gdp.loc[idx, 'Units'].unique())
    print('')

Inflation, average consumer prices
['Annual percentages of average consumer prices are year-on-year changes.']
['Percent change']

Unemployment rate
['Unemployment rate can be defined by either the national definition, the ILO harmonized definition, or the OECD harmonized definition. The OECD harmonized unemployment rate gives the number of unemployed persons as a percentage of the labor force (the total number of people employed plus unemployed). [OECD Main Economic Indicators, OECD, monthly] As defined by the International Labour Organization, unemployed workers are those who are currently not working but are willing and able to work for pay, currently available to work, and have actively searched for work. [ILO, http://www.ilo.org/public/english/bureau/stat/res/index.htm]']
['Percent of total labor force']

General government net lending/borrowing
['Net lending (+)/ borrowing (?) is calculated as revenue minus total expenditure. This is a core GFS balance that measures the extent to which general government is either putting financial resources at the disposal of other sectors in the economy and nonresidents (net lending), or utilizing the financial resources generated by other sectors and nonresidents (net borrowing). This balance may be viewed as an indicator of the financial impact of general government activity on the rest of the economy and nonresidents (GFSM 2001, paragraph 4.17). Note: Net lending (+)/borrowing (?) is also equal to net acquisition of financial assets minus net incurrence of liabilities.']
['Percent of GDP']

Current account balance
['Current account is all transactions other than those in financial and capital items. The major classifications are goods and services, income and current transfers. The focus of the BOP is on transactions (between an economy and the rest of the world) in goods, services, and income.']
['Percent of GDP']

So only `Inflation, average consumer prices` is given by an annual percentage change, the other variables needs to be transformed later. 

The dataframe for example for germany will look like this:

In [14]:
df_imf_woe_data =  get_imf_woe_data(df_weo_real_gdp, 'Germany', remove_na=False)
df_imf_woe_data[imf_woe_variables]

,"Inflation, average consumer prices",Unemployment rate,General government net lending/borrowing,Current account balance
1980,5.447,3.359,NaN,-1.782
1981,6.324,4.831,NaN,-0.684
1982,5.256,6.734,NaN,0.866
1983,3.284,8.099,NaN,0.666
1984,2.396,8.058,NaN,1.423
1985,2.084,8.124,NaN,2.662
1986,-0.125,7.834,NaN,4.024
1987,0.242,7.843,NaN,3.709
1988,1.274,7.735,NaN,4.317
1989,2.778,6.79,NaN,4.689
1990,2.687,6.155,NaN,3.131
1991,3.474,5.47,-3.189,-1.422
1992,5.046,6.592,-2.605,-1.183
1993,4.476,7.775,-3.095,-1.037
1994,2.717,8.425,-2.524,-1.5
1995,1.733,8.233,-9.432,-1.246
1996,1.274,8.908,-3.57,-0.676
1997,1.496,9.658,-2.942,-0.51
1998,0.607,9.383,-2.567,-0.711
1999,0.657,8.558,-1.719,-1.422
2000,1.413,7.95,-1.585,-1.761
2001,1.911,7.8,-3.025,-0.368
2002,1.295,8.6,-3.875,1.891
2003,1.084,9.708,-3.704,1.414
2004,1.75,10.333,-3.334,4.52
2005,1.939,11.008,-3.319,4.673
2006,1.795,10.042,-1.653,5.772
2007,2.29,8.567,0.261,6.861
2008,2.726,7.383,-0.116,5.692
2009,0.246,7.667,-3.151,5.836
2010,1.119,6.933,-4.379,5.744
2011,2.501,5.858,-0.881,6.213
2012,2.141,5.367,0.009,7.129
2013,1.607,5.233,0.04,6.557
2014,0.761,5.008,0.58,7.204
2015,0.671,4.625,0.943,8.59
2016,0.375,4.158,1.184,8.509
2017,1.711,3.758,1.242,7.824
2018,1.951,3.4,1.867,7.397
2019,1.346,3.158,1.449,7.146

### 1.2.3 OECD

The Organisation for Economic Co-operation and Development (OECD) provied also macroeconomic data in its [iLibrary]( https://www.oecd-ilibrary.org). The indicators can be browsed by theme and I choose 19 to use for my forecast. Each one is available by an `.csv` file. I load all of them together into one dataframe:

In [15]:
def get_oecd_data(path_oecd, country): 
 
    result = pd.DataFrame()
  
    
    for file_name in os.listdir(path_oecd):
    
        
        file = os.path.join(path_oecd, file_name)
        
        df_orig = pd.read_csv(file)
        unique_subjects = df_orig['SUBJECT'].unique()
    
        
        for subject in unique_subjects:
            
            
            df = df_orig.copy()
            df = df[df['LOCATION'] == country] 
            df = df[df['SUBJECT'] == subject]
            
            # if there is only one unique subject, the name is TOT
            if(len(unique_subjects) == 1):
                subject = file_name[:-4]
            
            
            df = df.rename({df.columns[6]: subject}, axis='columns')
            
            df = df.set_index('TIME')
            
            result = pd.concat([result, df[subject]], axis=1)           
    
    return result

In [16]:
path_oecd = r'C:\Users\hauer\Dropbox\CFDS\Project\data2\OECD'

df_oecd = get_oecd_data(path_oecd, 'USA')
df_oecd.tail()

,Air_Pollution,Crude_oil_production,CurrentAccountBalance,Electricity_generation,ExchangeR,Fertility_rates,GHG,Household_spending,NOMINAL,RENT,...,STINT,Tax_on_corporate_profits,Tax_on_goods_and_services,Tax_on_personal_income,TermsOfTrade,TradeGoodsExport,TradeGoodsImport,TradeServicesExport,TradeServicesImports,Working_age_population
2016,7.37633,446538.263,-2.109880,4119445.000,1.0,1.8,14.9,12769962.0,105.711763,103.772816,...,0.644167,1.949,4.299,10.387,101.649388,1451.022,2187.599,780531.0,511898.0,65.890
2017,7.36365,470360.949,-1.871310,4086002.602,1.0,1.8,14.6,13340354.0,112.336757,107.730991,...,1.152500,1.566,4.223,10.422,101.989233,1546.472,2339.885,830387.0,544836.0,65.628
2018,NaN,NaN,-2.185078,4236927.396,1.0,1.7,NaN,13993281.0,119.426500,111.627442,...,2.188333,0.998,4.303,10.037,102.492082,1665.688,2537.730,862434.0,562069.0,65.364
2019,NaN,NaN,-2.241142,NaN,1.0,NaN,NaN,14544601.0,125.599526,115.765067,...,NaN,0.957,4.296,10.143,NaN,1643.161,2497.532,875825.0,588359.0,NaN
2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

All of the variables are given absolute values for the specific year, so every variable needs to be transformed afterwards.
There are 182 countries or aggregated country groups available:

In [17]:
countries_oecd = set()

for file_name in os.listdir(path_oecd):
    file = os.path.join(path_oecd, file_name)
    df = pd.read_csv(file)
    countries_current = set(df['LOCATION'].unique())
    
    countries_oecd = countries_oecd.union(countries_current)

    
countries_oecd = list(countries_oecd)
len(countries_oecd)

183

In [18]:
countries_oecd

['MNE',
 'G-20',
 'JOR',
 'IRL',
 'MLT',
 'LBN',
 'ESP',
 'PAK',
 'KOR',
 'IRN',
 'BLR',
 'PNG',
 'MYS',
 'ZMB',
 'LSO',
 'FIN',
 'MWI',
 'SAU',
 'LBR',
 'CYP',
 'MUS',
 'OEU',
 'MOZ',
 'KEN',
 'ARM',
 'GNQ',
 'TLS',
 'PER',
 'KGZ',
 'NAM',
 'THA',
 'WLD',
 'IND',
 'PSE',
 'ZWE',
 'YEM',
 'AUS',
 'NZL',
 'GHA',
 'GMB',
 'BFA',
 'NIC',
 'LUX',
 'RWA',
 'TGO',
 'ARG',
 'MNG',
 'CAF',
 'PRT',
 'COG',
 'SVK',
 'HUN',
 'BWA',
 'JPN',
 'EU28',
 'SEN',
 'MLI',
 'COL',
 'GAB',
 'MAC',
 'CHN',
 'KHM',
 'MEX',
 'DNK',
 'BOL',
 'ISL',
 'LBY',
 'MDG',
 'DOM',
 'DZA',
 'NGA',
 'GRC',
 'BEN',
 'G-7',
 'HKG',
 'CMR',
 'EU',
 'MDA',
 'OMN',
 'SWZ',
 'UKR',
 'DEU',
 'COD',
 'LKA',
 'PHL',
 'ECU',
 'TZA',
 'SLE',
 'GBR',
 'LVA',
 'CRI',
 'G20',
 'HTI',
 'TJK',
 'KWT',
 'JAM',
 'GNB',
 'BRN',
 'AUT',
 'FRA',
 'TUN',
 'TKM',
 'AZE',
 'MMR',
 'LAO',
 'ARE',
 'TWN',
 'MRT',
 'PRK',
 'TUR',
 'EA19',
 'POL',
 'AGO',
 'NPL',
 'BRA',
 'ALB',
 'CAN',
 'BGR',
 'ZAF',
 'HND',
 'OECDE',
 'SLV',
 'EU27_2020',
 'NOR',
 'UGA',
 'QAT',
 'ETH',
 'NER',
 'CHE',
 'CUB',
 'BIH',
 'SDN',
 'EGY',
 'CHL',
 'EA17',
 'SYR',
 'TCD',
 'RUS',
 'VEN',
 'ITA',
 'SRB',
 'AFG',
 'GEO',
 'FJI',
 'UZB',
 'BEL',
 'PAN',
 'OECD',
 'URY',
 'HRV',
 'IRQ',
 'VNM',
 'ERI',
 'DEW',
 'TTO',
 'SWE',
 'ISR',
 'KAZ',
 'LTU',
 'GTM',
 'USA',
 'SGP',
 'IDN',
 'BHR',
 'EST',
 'CZE',
 'LIE',
 'EU27',
 'BGD',
 'ROU',
 'BDI',
 'MAR',
 'OAVG',
 'NLD',
 'CIV',
 'EA',
 'G7M',
 'MKD',
 'SOM',
 'PRY',
 'GIN',
 'SVN',
 'BTN']

Here is the mapping from the ISO country code that used the OECD to the country names that are used by the IMF:

In [19]:
path = r'C:\Users\hauer\Dropbox\CFDS\Project\data2\Mapping_country_codes.csv'
df_country_mapping =  pd.read_csv(path, sep = '\t')

df_country_mapping

      ID  ISO                           Country
0      1  AFG                       Afghanistan
1      2  ALB                           Albania
2      3  DZA                           Algeria
3      4  AGO                            Angola
4      5  ATG               Antigua and Barbuda
5      6  ARG                         Argentina
6      7  ARM                           Armenia
7      8  ABW                             Aruba
8      9  AUS                         Australia
9     10  AUT                           Austria
10    11  AZE                        Azerbaijan
11    12  BHS                       The Bahamas
12    13  BHR                           Bahrain
13    14  BGD                        Bangladesh
14    15  BRB                          Barbados
15    16  BLR                           Belarus
16    17  BEL                           Belgium
17    18  BLZ                            Belize
18    19  BEN                             Benin
19    20  BTN                            Bhutan
20    21  BOL                           Bolivia
21    22  BIH            Bosnia and Herzegovina
22    23  BWA                          Botswana
23    24  BRA                            Brazil
24    25  BRN                 Brunei Darussalam
25    26  BGR                          Bulgaria
26    27  BFA                      Burkina Faso
27    28  BDI                           Burundi
28    29  CPV                        Cabo Verde
29    30  KHM                          Cambodia
30    31  CMR                          Cameroon
31    32  CAN                            Canada
32    33  CAF          Central African Republic
33    34  TCD                              Chad
34    35  CHL                             Chile
35    36  CHN                             China
36    37  COL                          Colombia
37    38  COM                           Comoros
38    39  COD  Democratic Republic of the Congo
39    40  COG                 Republic of Congo
40    41  CRI                        Costa Rica
41    42  CIV                     Côte d'Ivoire
42    43  HRV                           Croatia
43    44  CYP                            Cyprus
44    45  CZE                    Czech Republic
45    46  DNK                           Denmark
46    47  DJI                          Djibouti
47    48  DMA                          Dominica
48    49  DOM                Dominican Republic
49    50  ECU                           Ecuador
50    51  EGY                             Egypt
51    52  SLV                       El Salvador
52    53  GNQ                 Equatorial Guinea
53    54  ERI                           Eritrea
54    55  EST                           Estonia
55    56  SWZ                          Eswatini
56    57  ETH                          Ethiopia
57    58  FJI                              Fiji
58    59  FIN                           Finland
59    60  FRA                            France
60    61  GAB                             Gabon
61    62  GMB                        The Gambia
62    63  GEO                           Georgia
63    64  DEU                           Germany
64    65  GHA                             Ghana
65    66  GRC                            Greece
66    67  GRD                           Grenada
67    68  GTM                         Guatemala
68    69  GIN                            Guinea
69    70  GNB                     Guinea-Bissau
70    71  GUY                            Guyana
71    72  HTI                             Haiti
72    73  HND                          Honduras
73    74  HKG                     Hong Kong SAR
74    75  HUN                           Hungary
75    76  ISL                           Iceland
76    77  IND                             India
77    78  IDN                         Indonesia
78    79  IRN          Islamic Republic of Iran
79    80  IRQ                              Iraq
80    81  IRL                           Ireland
81    82  ISR                            Israel
82    83  ITA                             Italy
83    84  JAM                           Jamaica
84    85  JPN                             Japan
85    86  JOR                            Jordan
86    87  KAZ                        Kazakhstan
87    88  KEN                             Kenya
88    89  KIR                          Kiribati
89    90  KOR                             Korea
90    91  UVK                            Kosovo
91    92  KWT                            Kuwait
92    93  KGZ                   Kyrgyz Republic
93    94  LAO                        Lao P.D.R.
94    95  LVA                            Latvia
95    96  LBN                           Lebanon
96    97  LSO                           Lesotho
97    98  LBR                           Liberia
98    99  LBY                             Libya
99   100  LTU                         Lithuania
100  101  LUX                        Luxembourg
101  102  MAC                         Macao SAR
102  103  MDG                        Madagascar
103  104  MWI                            Malawi
104  105  MYS                          Malaysia
105  106  MDV                          Maldives
106  107  MLI                              Mali
107  108  MLT                             Malta
108  109  MHL                  Marshall Islands
109  110  MRT                        Mauritania
110  111  MUS                         Mauritius
111  112  MEX                            Mexico
112  113  FSM                        Micronesia
113  114  MDA                           Moldova
114  115  MNG                          Mongolia
115  116  MNE                        Montenegro
116  117  MAR                           Morocco
117  118  MOZ                        Mozambique
118  119  MMR                           Myanmar
119  120  NAM                           Namibia
120  121  NRU                             Nauru
121  122  NPL                             Nepal
122  123  NLD                       Netherlands
123  124  NZL                       New Zealand
124  125  NIC                         Nicaragua
125  126  NER                             Niger
126  127  NGA                           Nigeria
127  128  MKD                   North Macedonia
128  129  NOR                            Norway
129  130  OMN                              Oman
130  131  PAK                          Pakistan
131  132  PLW                             Palau
132  133  PAN                            Panama
133  134  PNG                  Papua New Guinea
134  135  PRY                          Paraguay
135  136  PER                              Peru
136  137  PHL                       Philippines
137  138  POL                            Poland
138  139  PRT                          Portugal
139  140  PRI                       Puerto Rico
140  141  QAT                             Qatar
141  142  ROU                           Romania
142  143  RUS                            Russia
143  144  RWA                            Rwanda
144  145  WSM                             Samoa
145  146  SMR                        San Marino
146  147  STP             São Tomé and Príncipe
147  148  SAU                      Saudi Arabia
148  149  SEN                           Senegal
149  150  SRB                            Serbia
150  151  SYC                        Seychelles
151  152  SLE                      Sierra Leone
152  153  SGP                         Singapore
153  154  SVK                   Slovak Republic
154  155  SVN                          Slovenia
155  156  SLB                   Solomon Islands
156  157  SOM                           Somalia
157  158  ZAF                      South Africa
158  159  SSD                       South Sudan
159  160  ESP                             Spain
160  161  LKA                         Sri Lanka
161  162  KNA               St. Kitts and Nevis
162  163  LCA                         St. Lucia
163  164  VCT    St. Vincent and the Grenadines
164  165  SDN                             Sudan
165  166  SUR                          Suriname
166  167  SWE                            Sweden
167  168  CHE                       Switzerland
168  169  SYR                             Syria
169  170  TWN          Taiwan Province of China
170  171  TJK                        Tajikistan
171  172  TZA                          Tanzania
172  173  THA                          Thailand
173  174  TLS                       Timor-Leste
174  175  TGO                              Togo
175  176  TON                             Tonga
176  177  TTO               Trinidad and Tobago
177  178  TUN                           Tunisia
178  179  TUR                            Turkey
179  180  TKM                      Turkmenistan
180  181  TUV                            Tuvalu
181  182  UGA                            Uganda
182  183  UKR                           Ukraine
183  184  ARE              United Arab Emirates
184  185  GBR                    United Kingdom
185  186  USA                     United States
186  187  URY                           Uruguay
187  188  UZB                        Uzbekistan
188  189  VUT                           Vanuatu
189  190  VEN                         Venezuela
190  191  VNM                           Vietnam
191  192  YEM                             Yemen
192  193  ZMB                            Zambia
193  194  ZWE                          Zimbabwe
194  195  NaN                               NaN

## 1.3  World Economic Outlook 


The International Monetary Fund publishes predictions of the GDP growth in its World Economic Outlook. The data can is taken from [here](https://www.imf.org/en/Publications/WEO/weo-database/2020/October) in the related links Historical WEO Forecasts Database. The data is provided in an Excel file called `WEOhistorical.xlsx`. The IMF publishes the WEO twice a year in spring and in fall. I will use the prediction of the fall, as this closer to the next year and therefore the prediction should be more precise. The data is formated the following: 

| country | year   |F1990ngdp_rpch|
|------|--------|--------------|
|   germany  | 1988  | 4.08 |
|   germany  | 1989  | 2.96 |
|   germany  | 1990  | 1.98 |
|   germany  | 1991  | 2.44 |
|   germany  | 1992  | 3.42 |
|   germany  | 1993  | 3.45 |
|   germany  | 1994  | 3.42 |
|   germany  | 1995  | 3.40 |

This is for example the WEO in fall of 1990 for germany. There are two years of historical data and 6 years of forecast data. The forecast can be found in the column `F1990ngdp_rpch`. This is the same subject code as for the realised GDP. I will only use the forecast for the next year, so for 1990 if will use the predicted growth of the GDP in 1991. I extract the forecast for a certain country and prediciton horizon with the following function. First I load the Excel file into an pandas dataframe:

In [20]:
path = r'C:\Users\hauer\Dropbox\CFDS\Project\data2\WEOhistorical.xlsx'
df_weo =  pd.read_excel(path,sheet_name='ngdp_rpch')

The function for the extraction of the WEO is called `get_predictions_weo`:

In [21]:
def get_predictions_weo(df_weo, country, start_forecast, end_forecast):
       
    df = df_weo[df_weo['country'] == country]
    
    
    for col in df.columns:
        if 'S' in col:
            del df[col] 
            
    del df['WEO_Country_Code']     
    
    
    df = df[df['year'] >= start_forecast]
    
    
    predictions_weo = []
    years = np.arange(start_forecast, end_forecast+1, 1)
    
    for year in years:
       
        df_curr = df[df['year'] == year]
        
        year_WEO = year - 1 
        column = 'F' + str(year_WEO) + 'ngdp_rpch'
        y_pred_year = df_curr[column].values[0]
        
        predictions_weo.append(y_pred_year)
    
    predictions_weo = pd.Series(data = predictions_weo, index = years)
    
    return predictions_weo

Here is for example the WEO for germany for the years 2010 to 2018:

In [22]:
get_predictions_weo(df_weo, country = 'Germany', start_forecast =  2010, end_forecast = 2018)

2010    0.335834
2011    2.021567
2012    1.273123
2013    0.852179
2014    1.399657
2015    1.451330
2016    1.573023
2017    1.425094
2018    1.843451
dtype: float64

The WEO is available from 1980 for the following countries or aggregated country groups:

In [23]:
countries_woe = df_weo['country'].unique()
len(countries_woe)

199

In [24]:
countries_woe

array(['World', 'Advanced Economies', 'United States', 'United Kingdom',
       'Austria', 'Belgium', 'Denmark', 'France', 'Germany', 'San Marino',
       'Italy', 'Luxembourg', 'Netherlands', 'Norway', 'Sweden',
       'Switzerland', 'Canada', 'Japan', 'Euro area', 'Finland', 'Greece',
       'Iceland', 'Ireland', 'Malta', 'Portugal', 'Spain', 'Turkey',
       'Australia', 'New Zealand', 'South Africa',
       'Emerging Market and Developing Economies', 'Argentina', 'Bolivia',
       'Brazil', 'Chile', 'Colombia', 'Costa Rica', 'Dominican Republic',
       'Ecuador', 'El Salvador', 'Guatemala', 'Haiti', 'Honduras',
       'Mexico', 'Nicaragua', 'Panama', 'Paraguay', 'Peru', 'Uruguay',
       'Venezuela', 'Antigua and Barbuda', 'Bahamas, The', 'Aruba',
       'Barbados', 'Dominica', 'Grenada', 'Guyana', 'Belize', 'Jamaica',
       'Puerto Rico', 'St. Kitts and Nevis', 'St. Lucia',
       'St. Vincent and the Grenadines', 'Suriname',
       'Trinidad and Tobago', 'Bahrain', 'Cyprus', 'Iran', 'Iraq',
       'Israel', 'Jordan', 'Kuwait', 'Lebanon', 'Oman', 'Qatar',
       'Saudi Arabia', 'Syria', 'United Arab Emirates', 'Egypt', 'Yemen',
       'West Bank and Gaza', 'Afghanistan', 'Bangladesh', 'Bhutan',
       'Brunei Darussalam', 'Myanmar', 'Cambodia', 'Sri Lanka',
       'Taiwan Province of China', 'Hong Kong SAR', 'India', 'Indonesia',
       'Timor-Leste', 'Korea', 'Lao P.D.R.', 'Macao SAR', 'Malaysia',
       'Maldives', 'Nepal', 'Pakistan', 'Palau', 'Philippines',
       'Singapore', 'Thailand', 'Vietnam', 'Djibouti', 'Algeria',
       'Angola', 'Botswana', 'Burundi', 'Cameroon', 'Cabo Verde',
       'Central African Republic', 'Chad', 'Comoros',
       'Congo, Republic of', 'Congo, Democratic Republic of the', 'Benin',
       'Equatorial Guinea', 'Eritrea', 'Ethiopia', 'Gabon', 'Gambia, The',
       'Ghana', 'Guinea-Bissau', 'Guinea', "Côte d'Ivoire", 'Kenya',
       'Lesotho', 'Liberia', 'Libya', 'Madagascar', 'Malawi', 'Mali',
       'Mauritania', 'Mauritius', 'Morocco', 'Mozambique', 'Niger',
       'Nigeria', 'Zimbabwe', 'Rwanda', 'São Tomé and Príncipe',
       'Seychelles', 'Senegal', 'Sierra Leone', 'Somalia', 'Namibia',
       'Sudan', 'South Sudan', 'Eswatini', 'Tanzania', 'Togo', 'Tunisia',
       'Uganda', 'Burkina Faso', 'Zambia', 'Solomon Islands', 'Fiji',
       'Kiribati', 'Nauru', 'Vanuatu', 'Papua New Guinea', 'Samoa',
       'Tonga', 'Marshall Islands', 'Micronesia', 'Tuvalu', 'Armenia',
       'Azerbaijan', 'Belarus', 'Albania', 'Georgia', 'Kazakhstan',
       'Kyrgyz Republic', 'Bulgaria', 'Moldova', 'Russia', 'Tajikistan',
       'China', 'Turkmenistan', 'Ukraine', 'Uzbekistan', 'Czech Republic',
       'Slovak Republic', 'Estonia', 'Latvia', 'Serbia',
       'Montenegro, Rep. of', 'Hungary', 'Lithuania', 'Mongolia',
       'Croatia', 'Slovenia', 'North Macedonia', 'Bosnia and Herzegovina',
       'Poland', 'Kosovo', 'Romania'], dtype=object)

# 1.3 Joinig the datasets


Here I join the different data sets to get a dataframe for each country. The data is available from 1980 to 2019 expect for the OECD data sets. These are provided from 1970 to 2017 and hence I filter them to receive the time from 1980 to 2017. I use the pythonic try except block to select only countries, that have an correspondent ISO code in the OECD dataset.
I will save each individual dataframe in a dictionary. For later convenience I also rename the column of the real gdp.

In [25]:
database = {}

availabe_countries_woe = set(countries_woe_real).union(countries_woe)

for country in availabe_countries_woe:
    try:
        iso = df_country_mapping[df_country_mapping['Country'] == country]['ISO']
        iso = iso.values[0]
        
        df_real_gdp = get_gdp_real(df_weo_real_gdp, country)
        df_real_gdp = df_real_gdp[df_real_gdp.index <= 2017]
        
        df_imf_woe_data =  get_imf_woe_data(df_weo_real_gdp, country, remove_na=False)
        df_imf_woe_data = df_imf_woe_data[imf_woe_variables]
        df_imf_woe_data.index = df_imf_woe_data.index.astype(int)
        df_imf_woe_data = df_imf_woe_data[df_imf_woe_data.index <= 2017]
        
        df_oecd = get_oecd_data(path_oecd, iso)
        df_oecd = df_oecd[df_oecd.index >= 1980]
        df_oecd = df_oecd[df_oecd.index <= 2017]
        
        
        df = pd.concat([df_real_gdp, df_imf_woe_data, df_oecd], axis=1)
        
        df = df.rename(columns={"GDP real": "y"})
        
        database[country] = df

    except Exception as e:
        print('Error' + str(e) + ' for ' + str(country))

Errorindex 0 is out of bounds for axis 0 with size 0 for nan
Errorindex 0 is out of bounds for axis 0 with size 0 for Congo, Democratic Republic of the
Errorcould not convert string to float: '--' for Greece
Errorindex 0 is out of bounds for axis 0 with size 0 for Euro area
Errorindex 0 is out of bounds for axis 0 with size 0 for World
Errorindex 0 is out of bounds for axis 0 with size 0 for Advanced Economies
Errorindex 0 is out of bounds for axis 0 with size 0 for Montenegro, Rep. of
Errorcould not convert string to float: '--' for Angola
Errorcould not convert string to float: '--' for Gabon
Errorindex 0 is out of bounds for axis 0 with size 0 for Congo, Republic of
Errorindex 0 is out of bounds for axis 0 with size 0 for Emerging Market and Developing Economies
Errorcould not convert string to float: '--' for Ethiopia
Errorindex 0 is out of bounds for axis 0 with size 0 for West Bank and Gaza
Errorindex 0 is out of bounds for axis 0 with size 0 for Gambia, The
Errorcould not convert string to float: '--' for Mauritania
Errorindex 0 is out of bounds for axis 0 with size 0 for Bahamas, The
Errorindex 0 is out of bounds for axis 0 with size 0 for Iran

Now I have 189 dataframes that are ready to be analysed:

In [26]:
len(database.keys())

189

## Fixing data type

During the later analysis there occured problems with wrong datatypes. For example some vaules where saved as strings: `unsupported operand type(s) for /: 'str' and 'str'`. In this section I fix all kind of this problems. 

Here is a list of the issues which i fix in the same order in the following code: 
* Netherlands could not convert string to float: '--'
* Brazil could not convert string to float: '1,430.72'
* Hungary unsupported operand type(s) for /: 'str' and 'str'

In [27]:
def convert_string_series(x):
    try:
        return x.str.replace(',', '').astype(float)
    
    # this operation only works with string vaules, i was not able to filter the other dtypes
    # (that should only be float) but it did not work. 
    
    except:
        return x


database_fixed = {}


for country in database.keys():
    try: 
        # Netherlands could not convert string to float: '--'
        database_fixed[country] =  database[country].replace('--', np.nan)

        # Brazil could not convert string to float: '1,430.72'
        database_fixed[country] =  database[country].replace(',', '')

        # Hungary unsupported operand type(s) for /: 'str' and 'str'
        database_fixed[country]  = database[country].apply(convert_string_series)
        
       
    except Exception as e:
        print(country + " " + str(e))


database = database_fixed.copy()

## Filitering missing values

First I define variables that i need later on. I will describe them before I use them:

In [28]:
t_missing_percentage = 0.9
number_of_qualified_variables = 15

In [29]:
variables = database['France'].columns
missing_dict = {var:0 for var in variables}

In [30]:
number_of_observations = 0
for country in database.keys():
    df =  database[country]   
    number_of_observations += df.shape[0]

    for column in df.columns:
        column_current = df[column]
        number_of_missing_observations = sum(column_current.isnull())
        missing_dict[column] += number_of_missing_observations

In [31]:
df_missing = pd.DataFrame.from_dict(missing_dict, orient='index')
df_missing.columns = ['Number of missing entries']
df_missing['Percent of missing entries'] = df_missing['Number of missing entries'] / number_of_observations * 100
df_missing.sort_values(by='Percent of missing entries', ascending=1)

,Number of missing entries,Percent of missing entries
y,794,11.055416
"Inflation, average consumer prices",819,11.403509
Current account balance,1105,15.385686
Material_consumption,2142,29.824561
TOTMAT,2233,31.091618
General government net lending/borrowing,2309,32.149819
Crude_oil_production,2493,34.711779
GHG,2517,35.045948
NONNRGMAT,3431,47.772208
Unemployment rate,3764,52.408800
Patents_on_environment_technologies,4296,59.816207
ExchangeR,5148,71.679198
Population,5244,73.015873
Working_age_population,5244,73.015873
Fertility_rates,5246,73.043720
PPP,5314,73.990532
Air_Pollution,5322,74.101921
Household_spending,5524,76.914508
TradeGoodsExport,5698,79.337232
TradeGoodsImport,5699,79.351156
TermsOfTrade,5765,80.270120
MFG,5813,80.938457
Share_prices,5862,81.620718
Electricity_generation,5892,82.038429
RENT,5955,82.915622
Tax_on_goods_and_services,5959,82.971317
Tax_on_corporate_profits,5990,83.402952
Tax_on_personal_income,5990,83.402952
Short-term_interest_rates,6045,84.168755
STINT,6045,84.168755
InsurceSpending,6069,84.502924
NOMINAL,6080,84.656085
Pension_funds_assets,6107,85.032025
TradeServicesExport,6117,85.171261
TradeServicesImports,6141,85.505430
CONSTR,6168,85.881370
LTINT,6183,86.090226
Long-term_interest_rates,6183,86.090226
CurrentAccountBalance,6189,86.173768
Labour_compensation_per_hour_worked,6210,86.466165
ProtectedArea,6337,88.234475
OilImport,6345,88.345865

How many missing values are there for each country in total:

In [32]:
df_missing_countries = pd.DataFrame(columns=['country', 'Percent of missing entries'])
   


for country in database.keys():
    df =  database[country] 
    N, p = df.shape
    number_of_entries = N * p
    number_of_missing = df.isna().sum().sum()
    percent_of_missing = number_of_missing / number_of_entries
    
    df_missing_countries = pd.concat([pd.DataFrame([[country , percent_of_missing]],
                                                        columns=df_missing_countries.columns),
                                         df_missing_countries],ignore_index=True)


df_missing_countries.sort_values(by='Percent of missing entries', ascending=1)

                              country  Percent of missing entries
149                     United States                    0.053258
154                            Canada                    0.055138
33                          Australia                    0.062030
116                       New Zealand                    0.073308
59                     United Kingdom                    0.102757
159                            France                    0.111529
56                             Sweden                    0.117168
172                           Germany                    0.117794
25                              Spain                    0.119048
93                        Switzerland                    0.122807
161                           Belgium                    0.125313
118                             Italy                    0.125940
153                            Norway                    0.132206
68                              Japan                    0.145990
22                        Netherlands                    0.147243
100                             Korea                    0.147870
19                            Denmark                    0.148496
26                            Finland                    0.148496
186                           Ireland                    0.155388
165                           Austria                    0.168546
121                          Portugal                    0.179825
107                           Iceland                    0.223058
74                             Mexico                    0.242481
135                      South Africa                    0.248120
92                             Israel                    0.250000
66                         Luxembourg                    0.260652
13                             Turkey                    0.291980
57                            Hungary                    0.307644
10                             Poland                    0.312030
139                          Colombia                    0.318296
96                              Chile                    0.321429
77                     Czech Republic                    0.328947
11                    Slovak Republic                    0.385338
42                           Slovenia                    0.406015
24                             Latvia                    0.434211
23                            Estonia                    0.436717
136                            Brazil                    0.442356
120                             India                    0.447995
34                          Indonesia                    0.449875
174                        Costa Rica                    0.454261
60                          Lithuania                    0.463659
99                              China                    0.483709
79                             Russia                    0.484336
117                         Argentina                    0.558271
75                       Saudi Arabia                    0.563283
2                             Romania                    0.601504
160                          Bulgaria                    0.612155
58                             Cyprus                    0.644110
12                          Singapore                    0.652256
72                               Peru                    0.661654
41                              Malta                    0.669173
104                           Croatia                    0.677945
164                           Morocco                    0.709273
8                       Hong Kong SAR                    0.734962
142                            Zambia                    0.737469
71                           Malaysia                    0.744987
46                           Paraguay                    0.748747
183                           Jamaica                    0.749373
84                           Pakistan                    0.750627
36                             Panama                    0.751253
129                       Philippines                    0.751880
114                            Jordan                    0.751880
82                            Algeria                    0.753133
141                Dominican Republic                    0.753133
54                Trinidad and Tobago                    0.753133
158          Islamic Republic of Iran                    0.754386
185                         Sri Lanka                    0.754386
182                          Thailand                    0.755013
53                            Ecuador                    0.755639
47                          Venezuela                    0.755639
163                       El Salvador                    0.756266
148                             Egypt                    0.760652
80                             Kuwait                    0.760652
27                            Tunisia                    0.761905
130                           Bolivia                    0.761905
178                          Honduras                    0.761905
155                           Uruguay                    0.762531
124                           Vietnam                    0.763784
32                              Kenya                    0.763784
64                          Nicaragua                    0.768170
105                        Bangladesh                    0.772556
122                             Ghana                    0.772556
7                United Arab Emirates                    0.775689
184                           Lebanon                    0.777569
119                           Bahrain                    0.779449
166                        Madagascar                    0.781328
162                        Mozambique                    0.783208
44                          Guatemala                    0.784461
169                          Tanzania                    0.784461
156                             Qatar                    0.785088
137                           Senegal                    0.785714
175                              Oman                    0.786967
150                 Republic of Congo                    0.787594
170                           Nigeria                    0.788221
115                              Togo                    0.788221
187                 Brunei Darussalam                    0.788221
101                             Libya                    0.789474
63                              Benin                    0.789474
168                          Cameroon                    0.791353
176                          Mongolia                    0.791980
97                      Côte d'Ivoire                    0.793233
102  Democratic Republic of the Congo                    0.794486
28                              Syria                    0.794486
61                              Haiti                    0.795113
125                          Botswana                    0.795739
52                            Albania                    0.800752
134                           Ukraine                    0.803258
123                             Nepal                    0.805764
17                            Belarus                    0.808271
167                          Zimbabwe                    0.809524
51                          Mauritius                    0.810777
87                            Moldova                    0.810777
37           Taiwan Province of China                    0.812657
131                        Kazakhstan                    0.813283
146                           Myanmar                    0.814536
49                         Azerbaijan                    0.814536
98                            Georgia                    0.815163
132                             Niger                    0.815163
35                            Namibia                    0.816416
55                               Fiji                    0.817043
85                              Sudan                    0.818296
89                              Yemen                    0.819549
5                             Armenia                    0.820802
21                    Kyrgyz Republic                    0.821429
40                             Bhutan                    0.823308
50                         Uzbekistan                    0.825188
179                          Eswatini                    0.829574
157                        Tajikistan                    0.830827
145                  Papua New Guinea                    0.832080
133                   North Macedonia                    0.832707
113                      Burkina Faso                    0.833333
177          Central African Republic                    0.833960
88                               Iraq                    0.835213
143                            Serbia                    0.835840
0                            Cambodia                    0.836466
108                 Equatorial Guinea                    0.836466
76                            Burundi                    0.837093
127                            Guinea                    0.837719
90                       Turkmenistan                    0.838346
30                             Rwanda                    0.838346
173                           Lesotho                    0.842105
31                         Lao P.D.R.                    0.842105
15                               Mali                    0.842732
38                             Uganda                    0.842732
81                       Sierra Leone                    0.845865
65                             Malawi                    0.845865
147                           Eritrea                    0.847744
48                         The Gambia                    0.848371
83                               Chad                    0.848371
20                      Guinea-Bissau                    0.854637
103            Bosnia and Herzegovina                    0.875940
151                        Cabo Verde                    0.889724
111                          Barbados                    0.890351
188                       The Bahamas                    0.890977
16                         Seychelles                    0.892231
70              São Tomé and Príncipe                    0.893484
18                           Suriname                    0.895990
128                            Belize                    0.897243
69                            Liberia                    0.901629
106                   Solomon Islands                    0.904762
4                             Comoros                    0.907268
29                        Afghanistan                    0.908521
180                          Kiribati                    0.911028
62                           Maldives                    0.911028
45                        Timor-Leste                    0.911654
152                           Vanuatu                    0.911654
43                              Samoa                    0.912281
138                            Guyana                    0.915414
171                             Tonga                    0.916667
6      St. Vincent and the Grenadines                    0.926065
9                 St. Kitts and Nevis                    0.926065
73                        Puerto Rico                    0.927318
109                         St. Lucia                    0.929198
112                        Montenegro                    0.929825
67                            Grenada                    0.932331
3                 Antigua and Barbuda                    0.932331
110                          Dominica                    0.932331
140                          Djibouti                    0.932957
14                              Aruba                    0.933584
95                          Macao SAR                    0.937970
1                          Micronesia                    0.943609
144                  Marshall Islands                    0.952381
126                            Kosovo                    0.952381
94                            Somalia                    0.955514
86                              Palau                    0.956140
91                         San Marino                    0.958020
78                             Tuvalu                    0.959273
39                              Nauru                    0.971805
181                       South Sudan                    0.983709

Filtering out countries that have more than 50 % missing values:

In [33]:
database_filtered_countries = {}


for country in database.keys():
    df =  database[country] 
    N, p = df.shape
    number_of_entries = N * p
    number_of_missing = df.isna().sum().sum()
    percent_of_missing = number_of_missing / number_of_entries
    
    if percent_of_missing >= 0.75:
        continue
    
    database_filtered_countries[country] = df
len(database_filtered_countries.keys())

58

Next i want to analyse how many values are missing. So I can decide which of the variables I will use for the models. To get an overview I count the number of missing values for all variables of all countries. To do this, I create a dictionary with all varibales available as keys. Then I only continue with the top 10 columns that are filed with values:

In [34]:
variables = database_filtered_countries['France'].columns
missing_dict = {var:0 for var in variables}

number_of_observations = 0
for country in database_filtered_countries.keys():
    df =  database_filtered_countries[country]   
    number_of_observations += df.shape[0]

    for column in df.columns:
        column_current = df[column]
        number_of_missing_observations = sum(column_current.isnull())
        missing_dict[column] += number_of_missing_observations 
        
df_missing = pd.DataFrame.from_dict(missing_dict, orient='index')
df_missing.columns = ['Number of missing entries']
df_missing['Percent of missing entries'] = df_missing['Number of missing entries'] / number_of_observations * 100
df_missing.sort_values(by='Percent of missing entries', ascending=1)

,Number of missing entries,Percent of missing entries
GHG,56,2.540835
Crude_oil_production,60,2.722323
y,134,6.079855
"Inflation, average consumer prices",135,6.125227
Current account balance,151,6.851180
ExchangeR,253,11.479129
Population,266,12.068966
Working_age_population,266,12.068966
Fertility_rates,268,12.159710
Unemployment rate,274,12.431942
Patents_on_environment_technologies,341,15.471869
PPP,385,17.468240
TOTMAT,509,23.094374
Material_consumption,509,23.094374
General government net lending/borrowing,567,25.725953
Household_spending,575,26.088929
TradeGoodsExport,720,32.667877
TradeGoodsImport,721,32.713249
TermsOfTrade,787,35.707804
MFG,835,37.885662
NONNRGMAT,840,38.112523
Share_prices,884,40.108893
Electricity_generation,914,41.470054
RENT,977,44.328494
Tax_on_goods_and_services,981,44.509982
Tax_on_personal_income,1012,45.916515
Tax_on_corporate_profits,1012,45.916515
Short-term_interest_rates,1067,48.411978
STINT,1067,48.411978
NOMINAL,1102,50.000000
InsurceSpending,1130,51.270417
TradeServicesExport,1139,51.678766
TradeServicesImports,1163,52.767695
CONSTR,1190,53.992740
LTINT,1205,54.673321
Long-term_interest_rates,1205,54.673321
CurrentAccountBalance,1211,54.945554
Labour_compensation_per_hour_worked,1232,55.898367
Pension_funds_assets,1336,60.617060
OilImport,1367,62.023593
Air_Pollution,1520,68.965517
ProtectedArea,1541,69.918330

Selecting the top 16 columns, because y is included.

In [35]:
df_missing = df_missing.sort_values(by='Percent of missing entries', ascending=1)

selected_columns = df_missing.index[0:15]
selected_columns.values

array(['GHG', 'Crude_oil_production', 'y',
       'Inflation, average consumer prices', 'Current account balance',
       'ExchangeR', 'Population', 'Working_age_population',
       'Fertility_rates', 'Unemployment rate',
       'Patents_on_environment_technologies', 'PPP', 'TOTMAT',
       'Material_consumption', 'General government net lending/borrowing'],
      dtype=object)

Ordering the columns new, because y has to be in first place and create a new database:

In [36]:
columns = ['y','GHG', 'Crude_oil_production',
       'Inflation, average consumer prices', 'Current account balance',
       'ExchangeR', 'Population', 'Working_age_population',
       'Fertility_rates', 'Unemployment rate',
       'Patents_on_environment_technologies', 'PPP', 'TOTMAT',
       'Material_consumption', 'General government net lending/borrowing']

database_filtered_columns = {}

for country in database_filtered_countries.keys():
    df = database_filtered_countries[country]
    database_filtered_columns[country] = df[columns]

# Spliting the dataset

The reference for this section is the book "The Elements of Statistical Learning" from Hastie et. al. 

To obtain an accurate Data Science process, it is necessary to split the whole dataset in certain subsets.  This is important for two reasons:

* Model selection: estimating the performance of different models in order to choose the best one. The term model selection also includes the tuning of the hyperparameters, if you define a model as the tupel consisting of the data used for training, the concrete typ of model or algorithm and the hyperparameters of the later. 
* Model assessment: having chosen a final model, estimating its prediction error (generalization error) on new data.

The data is split into a training, validation and test set. The training set is used to fit the model and the validation set is used to calculate the validation error. This error gives an estimate of its prediction error. The test is kept in an "vault" and is brought out only at the very end of the analysis. After using the test set, no changes in any step is allowed. Otherwise the test error will underestimate the true test error. With this test error the selection of the best model is done. 

Another thing in this procedure is very important: Every step in the analysis needs to be performed on the training set only. For example in the next section I will impute missing values. I will fit the algorithim that performes the imputation on the training set and predict the values then for both the training and test set. Otherwise the wrong applicaton of the impuation would also underestimate the validation or test error, because for the imputation there would be more information available than in an real life scenario. New data is completly unseen and only the training data is available for fitting the model in generall. 

This is also noted in the section 7.10.2 The Wrong and Right Way to Do Cross-validation. Even though I am not doing cross validation, this description suits the application in this project. 


I will use the years 2014 - 2017 as the test set. I will calculate  the performance on the very end and after i will not change anythin in the procedure. The years  2010 - 2013 will be the validation set and will be use for tuning the hypterparameter.

In [37]:
def split_dataset(database):
    database_training = {}
    database_validation = {}
    database_test = {}


    for country in database.keys():


        df = database[country]

        #df_test = df[df.index > 2013]
        #df_validation = df[(df.index > 2009) & (df.index <= 2013)]
        #df_training = df[df.index <= 2009]
        
#         df_test = df[df.index > 2012]
#         df_validation = df[(df.index > 2008) & (df.index <= 2012)]
#         df_training = df[df.index <= 2008]
        
        df_test = df[df.index > 2010]
        df_validation = df[(df.index > 2004) & (df.index <= 2010)]
        df_training = df[df.index <= 2004]

        database_training[country] = df_training
        database_validation[country] = df_validation
        database_test[country] = df_test
        
    return (database_training, database_validation, database_test)


database_training, database_validation, database_test = split_dataset(database_filtered_columns)

### kNN

Example for 'United States'. knn performes as mean, if all values are NaN.

In [57]:
database_training[' ']

KeyError: ' '

In [40]:
from sklearn.impute import KNNImputer
df = database_training['United States']

imputer = KNNImputer(missing_values=np.nan, n_neighbors=5, weights="uniform")

imputer.fit(df)

df_data = imputer.transform(df)

df = pd.DataFrame(data = df_data, columns = df.columns, index = df.index)
df

,y,GHG,Crude_oil_production,"Inflation, average consumer prices",Current account balance,ExchangeR,Population,Working_age_population,Fertility_rates,Unemployment rate,Patents_on_environment_technologies,PPP,TOTMAT,Material_consumption,General government net lending/borrowing
1980,-0.257,20.2,437343.198,13.502,0.081,1.0,227.224681,66.114,1.8,7.175,7.61,1.0,1.2348,24.9571,-3.33775
1981,2.538,19.7,434876.812,10.378,0.157,1.0,229.465714,66.237,1.8,7.617,7.31,1.0,1.2665,24.7176,-3.33775
1982,-1.802,18.6,438781.579,6.158,-0.165,1.0,231.664458,66.279,1.8,9.708,6.65,1.0,1.3369,22.7791,-3.33775
1983,4.584,18.3,440767.473,3.160,-1.065,1.0,233.791994,66.282,1.8,9.600,6.42,1.0,1.4141,22.3109,-3.33775
1984,7.237,19.0,452804.508,4.368,-2.337,1.0,235.824902,66.347,1.8,7.508,6.40,1.0,1.3495,24.8367,-3.33775
1985,4.169,18.9,456267.966,3.528,-2.723,1.0,237.923795,66.396,1.8,7.192,6.25,1.0,1.3378,25.8564,-3.33775
1986,3.463,18.6,442489.072,1.944,-3.214,1.0,240.132887,66.459,1.8,7.000,6.18,1.0,1.3740,25.8035,-3.33775
1987,3.460,19.1,425489.688,3.578,-3.309,1.0,242.288918,66.368,1.9,6.175,5.69,1.0,1.3498,26.9212,-3.33775
1988,4.177,19.8,415979.499,4.100,-2.314,1.0,244.498982,66.227,1.9,5.492,5.79,1.0,1.3852,27.0722,-3.33775
1989,3.673,19.8,388003.681,4.791,-1.763,1.0,246.819230,66.006,2.0,5.258,6.04,1.0,1.4436,26.6778,-3.33775
1990,1.886,19.2,374866.670,5.419,-1.324,1.0,249.622814,65.791,2.1,5.617,6.08,1.0,1.4211,27.3489,-3.33775
1991,-0.108,18.8,377987.150,4.216,0.047,1.0,252.980941,65.587,2.1,6.850,6.34,1.0,1.4863,25.8727,-3.33775
1992,3.522,18.8,366480.641,3.042,-0.792,1.0,256.514224,65.475,2.0,7.492,6.55,1.0,1.4798,26.6441,-3.33775
1993,2.753,19.0,348942.928,2.970,-1.237,1.0,259.918588,65.374,2.0,6.908,6.83,1.0,1.5076,26.6093,-3.33775
1994,4.029,19.1,339510.195,2.596,-1.669,1.0,263.125821,65.364,2.0,6.100,6.39,1.0,1.4506,28.4730,-3.33775
1995,2.684,19.0,334314.908,2.805,-1.487,1.0,266.278393,65.434,2.0,5.592,5.90,1.0,1.5124,27.7337,-3.33775
1996,3.772,19.4,330369.878,2.937,-1.546,1.0,269.394284,65.534,2.0,5.408,5.57,1.0,1.5205,28.2873,-3.33775
1997,4.447,20.1,328807.572,2.338,-1.641,1.0,272.646925,65.710,2.0,4.942,5.32,1.0,1.5146,29.2911,-3.33775
1998,4.481,20.1,318626.750,1.547,-2.373,1.0,275.854104,65.887,2.0,4.500,5.31,1.0,1.5200,30.1117,-3.33775
1999,4.753,19.9,299750.952,2.193,-2.994,1.0,279.040168,66.043,2.0,4.217,5.39,1.0,1.5887,29.8140,-3.33775
2000,4.127,20.3,297512.886,3.367,-3.935,1.0,282.162411,66.207,2.1,3.967,5.64,1.0,1.6429,29.6828,-3.33775
2001,0.999,20.0,295670.563,2.817,-3.683,1.0,284.968955,66.403,2.0,4.742,5.91,1.0,1.6812,28.9986,-0.53700
2002,1.742,19.3,292823.901,1.596,-4.122,1.0,287.625193,66.593,2.0,5.783,6.60,1.0,1.7559,27.9860,-3.81200
2003,2.861,19.3,289518.467,2.298,-4.527,1.0,290.107933,66.739,2.0,5.992,6.47,1.0,1.8005,27.8275,-4.76400
2004,3.799,19.4,276931.156,2.668,-5.171,1.0,292.805298,66.921,2.0,5.542,6.91,1.0,1.7694,29.1377,-4.23800

For the validation and training set the `transform` function is also applied to impute missing values for these datapoints:

In [41]:
df = database_validation['United States']
df_data = imputer.transform(df)
df_validation = pd.DataFrame(data = df_data, columns = df.columns, index = df.index)
df_validation

,y,GHG,Crude_oil_production,"Inflation, average consumer prices",Current account balance,ExchangeR,Population,Working_age_population,Fertility_rates,Unemployment rate,Patents_on_environment_technologies,PPP,TOTMAT,Material_consumption,General government net lending/borrowing
2005,3.513,19.3,263918.138,3.366,-5.716,1.0,295.516599,67.118,2.1,5.083,7.39,1.0,1.7790,29.7308,-3.069
2006,2.855,18.7,260029.939,3.222,-5.834,1.0,298.379912,67.262,2.1,4.608,8.10,1.0,1.8613,28.9556,-2.029
2007,1.876,18.8,258101.855,2.871,-4.920,1.0,301.231207,67.298,2.1,4.617,9.60,1.0,2.0009,27.1810,-2.910
2008,-0.137,18.1,252986.129,3.815,-4.631,1.0,304.093966,67.219,2.1,5.800,11.28,1.0,2.1353,25.1942,-6.630
2009,-2.537,16.7,273202.080,-0.320,-2.578,1.0,306.771529,67.170,2.0,9.283,12.39,1.0,2.3377,22.2216,-13.197
2010,2.564,17.3,279225.018,1.637,-2.877,1.0,309.326085,67.128,1.9,9.608,12.64,1.0,2.3603,22.3759,-11.024

In [42]:
df = database_test['United States']
df_data = imputer.transform(df)
df_test = pd.DataFrame(data = df_data, columns = df.columns, index = df.index)
df_test

,y,GHG,Crude_oil_production,"Inflation, average consumer prices",Current account balance,ExchangeR,Population,Working_age_population,Fertility_rates,Unemployment rate,Patents_on_environment_technologies,PPP,TOTMAT,Material_consumption,General government net lending/borrowing
2011,1.551,16.4,287590.382,3.140,-2.867,1.0,311.580009,67.096,1.9,8.933,12.19,1.0,2.4196,21.9833,-9.703
2012,2.249,15.6,332009.679,2.073,-2.635,1.0,313.874218,66.786,1.9,8.075,12.36,1.0,2.7235,19.8132,-8.028
2013,1.842,15.9,380518.664,1.466,-2.078,1.0,316.057727,66.554,1.9,7.358,11.50,1.0,2.6794,20.3572,-4.564
2014,2.526,15.8,446109.689,1.615,-2.084,1.0,318.386421,66.322,1.9,6.158,11.25,1.0,2.7270,20.3609,-4.034
2015,2.908,15.3,472634.851,0.121,-2.237,1.0,320.742673,66.120,1.8,5.275,11.11,1.0,2.8767,19.7586,-3.566
2016,1.638,14.9,446538.263,1.261,-2.289,1.0,323.071342,65.890,1.8,4.875,11.06,1.0,2.9983,19.1535,-4.269
2017,2.370,14.6,470360.949,2.138,-2.252,1.0,325.147121,65.628,1.8,4.342,10.41,1.0,3.1449,18.5679,-4.471

Finally this step is done for the whole dataset:

In [43]:
database_training_imputed = {}
database_validation_imputed = {}
database_test_imputed = {}

imputer = KNNImputer(missing_values=np.nan, n_neighbors=5, weights="uniform")

for country in database_filtered_columns.keys():   
  
    try:
        
        df_current = database_training[country]
        imputer.fit(df_current)
        df_data = imputer.transform(df_current)
        database_training_imputed[country] = pd.DataFrame(data = df_data,
                                                          columns = df_current.columns,
                                                          index = df_current.index)
        
        df_current = database_validation[country]
        df_data = imputer.transform(df_current)
        database_validation_imputed[country] = pd.DataFrame(data = df_data,
                                                            columns = df_current.columns,
                                                            index = df_current.index)
        
        df_current = database_test[country]
        df_data = imputer.transform(df_current)
        database_test_imputed[country] = pd.DataFrame(data = df_data,
                                                      columns = df_current.columns,
                                                      index = df_current.index)
        
    except Exception as e:
        print(country + " " + str(e))

Jamaica Shape of passed values is (25, 10), indices imply (25, 15)
Morocco Shape of passed values is (25, 12), indices imply (25, 15)
Bulgaria could not convert string to float: '--'
Norway Shape of passed values is (25, 13), indices imply (25, 15)
Zambia Shape of passed values is (25, 11), indices imply (25, 15)
India Shape of passed values is (25, 14), indices imply (25, 15)
Peru Shape of passed values is (25, 13), indices imply (25, 15)
Malaysia Shape of passed values is (25, 10), indices imply (25, 15)
Paraguay Shape of passed values is (25, 10), indices imply (25, 15)
Netherlands could not convert string to float: '--'
Singapore Shape of passed values is (25, 13), indices imply (25, 15)
Hong Kong SAR Shape of passed values is (25, 10), indices imply (25, 15)

## Preprocess Data

The different variables have different absolute vaules. Some machine learning models will have problems with this type of input. That is the reason I preprocess the data as follows:

First I want to have only growth rates. For a time series $ X = (x_{1}, ..., x_{n})$ the growth rate for $x_{i}$ is defined as:

\begin{equation}
\hat{x}_{i} = \frac{x_{i}}{x_{i-1}}
\end{equation}
    
The first value of the original serires will not be mapped. Another issue occoures when using only this transformation. I compare a 10 % increase and a 10 % decrease of a certain vaule. Let's denothe the increase with $\hat{x}_{I}$ and the decrease with $\hat{x}_{D}$. Now the following applies:

\begin{equation}
\hat{x}_{I} = 1.1 \\
\hat{x}_{D} = 0.9
\end{equation}
 
 so
 
 \begin{equation}
|\hat{x}_{I}| \neq |\hat{x}_{D}|.
\end{equation}

In order to obation the same absolute value for both directions, I will apply a logarithmic transformation:

\begin{equation}
\hat{x}_{i} = \ln(\frac{x_{i}}{x_{i-1}})
\end{equation}

To avoid arguments that are not defined for the logarithm I shift the fraction by $|\min_i(x_{i})|  + 0.001$:
 
\begin{equation}
\hat{x}_{i} = \ln(\frac{x_{i}}{x_{i-1}} + |\min_i(x_{i})| + 0.001)
\end{equation}

In same cases there is $x_{i} = x_{i-1} = 0$ which will cause an error because of divisin by zero. I add a some constant to avoid this problem.  

As there are no statistics from the dataset involved, this transformation can be appplied to the whole dataset. Therefore I first glue the training, validation and test dataset together:

In [44]:
def combine_datasets(database_training, database_validation, database_test):
    database_complete = {}

    for country in database_training.keys():
        database_complete[country] = database_training[country].append(database_validation[country]).append(database_test[country])
        
    return database_complete

database_imputed = combine_datasets(database_training_imputed, database_validation_imputed, database_test_imputed)

With this function I transform the whole dataframe

In [45]:
def convert_time_series_to_relative(df):
    # Assings each t the Values of ln(X_t / X_(t-1))
    # X_0 will be dropped
    
    df_new = df.iloc[1:, :].copy()
    
    for variable in df.columns:
        try:
            
            if not (df[variable] != 0).all():
                df[variable] = df[variable] + 0.001
                
            #Check if this tranformation is correct!
           # df_new[variable] = df[variable].iloc[:-1].values / df[variable].iloc[1:].values
            df_new[variable] = df[variable].iloc[1:].values / df[variable].iloc[:-1].values 
            
            df_new[variable] = np.log(df_new[variable] + 0.001 + np.abs(np.min(df_new[variable])))
        except Exception as e:
            print(country + " " + str(e))
        
    return df_new

and apply it to the database

In [46]:
database_transformed = {}

for country in database_imputed.keys():
    
    database_transformed[country] = convert_time_series_to_relative(database_imputed[country])

## Index Shift of the data

reference: paper crystal ball; shifting index for supervised learning, tuples look like (x_t-1, y_t)

In [47]:
def preprocess_for_supervised_learning(df):
     
    df_y = df.loc[:, 'y']
    df_variables = df.drop(['y'], axis=1)
    
    df_variables.index = df_variables.index - 1 
   
    df = pd.DataFrame(df_y).join(df_variables, how='inner')
    
    return df


df = database_transformed['Germany']
df_supervised = preprocess_for_supervised_learning(df)
df_supervised.head()

,y,GHG,Crude_oil_production,"Inflation, average consumer prices",Current account balance,ExchangeR,Population,Working_age_population,Fertility_rates,Unemployment rate,Patents_on_environment_technologies,PPP,TOTMAT,Material_consumption,General government net lending/borrowing
1981,1.981155,0.632298,0.616743,1.018168,1.354160,0.594607,0.683946,0.697905,0.624690,0.806413,0.633409,0.661480,0.656005,0.660662,0.368417
1982,-6.907755,0.660700,0.622615,0.940714,1.776416,0.582665,0.683105,0.697649,0.588342,0.717180,0.636903,0.663734,0.656005,0.660662,0.368417
1983,1.646981,0.668897,0.631374,0.980804,1.984612,0.616934,0.682684,0.696084,0.624690,0.610245,0.640212,0.661181,0.656005,0.660662,0.368417
1984,2.195223,0.660570,0.649201,1.032039,1.947378,0.572700,0.683299,0.693316,0.624690,0.617418,0.705977,0.664048,0.656005,0.660662,0.368417
1985,2.071950,0.660539,0.632125,0.629685,1.894802,0.389478,0.684657,0.691693,0.624690,0.593464,0.669449,0.674149,0.656005,0.660662,0.368417

In [48]:
df.head()

,y,GHG,Crude_oil_production,"Inflation, average consumer prices",Current account balance,ExchangeR,Population,Working_age_population,Fertility_rates,Unemployment rate,Patents_on_environment_technologies,PPP,TOTMAT,Material_consumption,General government net lending/borrowing
1981,1.981155,0.640923,0.621216,1.130759,1.708998,0.684085,0.685195,0.697405,0.590653,0.826003,0.644128,0.644167,0.656005,0.660662,0.368417
1982,-6.907755,0.632298,0.616743,1.018168,1.354160,0.594607,0.683946,0.697905,0.624690,0.806413,0.633409,0.661480,0.656005,0.660662,0.368417
1983,1.646981,0.660700,0.622615,0.940714,1.776416,0.582665,0.683105,0.697649,0.588342,0.717180,0.636903,0.663734,0.656005,0.660662,0.368417
1984,2.195223,0.668897,0.631374,0.980804,1.984612,0.616934,0.682684,0.696084,0.624690,0.610245,0.640212,0.661181,0.656005,0.660662,0.368417
1985,2.071950,0.660570,0.649201,1.032039,1.947378,0.572700,0.683299,0.693316,0.624690,0.617418,0.705977,0.664048,0.656005,0.660662,0.368417

Applying it to the whole database:

In [49]:
database_supervised = {}

for country in database_transformed.keys():
    
    database_supervised[country] = preprocess_for_supervised_learning(database_transformed[country])

Finally I split the dataset again to obtain the training, validation and test sets:

In [50]:
database_training, database_validation, database_test = split_dataset(database_transformed)
database_training_sv, database_validation_sv, database_test_sv = split_dataset(database_supervised)

## Standardization 

Finally, transform data so that every colun has 0 mean and sdtdev 1. This is especially important for neural networks.

In [51]:
def standardization(df_training, df_validation, df_test):
     
    scaler = preprocessing.StandardScaler().fit(df_training)
    
    return scaler.transform(df_training), scaler.transform(df_validation), scaler.transform(df_test), scaler

Applying it to the whole dataset and keeping track of the scaler instance for each country:

In [52]:
database_training_sv_standard = {}
database_validation_sv_standard = {}
database_test_sv_standard = {}
database_scaler = {}

for country in database_training_sv.keys():
    
    tr, val, test, scaler = standardization(database_training_sv[country], database_validation_sv[country], database_test_sv[country])
    
    database_training_sv_standard[country] = pd.DataFrame(tr)
    database_validation_sv_standard[country] = pd.DataFrame(val)
    database_test_sv_standard[country]  = pd.DataFrame(test)
    database_scaler[country] = scaler

I also serialize the whole database, so I can start coding without rerunning the whole data handling.

In [53]:
database_dir = os.path.join(r'C:/Users/hauer/Documents/Repositories/cfds_project', 'database_new.pickle')
with open(database_dir, 'wb') as f:
    save = {
        'database_training': database_training,
        'database_validation': database_validation,
        'database_test': database_test,
        'database_training_sv': database_training_sv,
        'database_validation_sv': database_validation_sv,
        'database_test_sv': database_test_sv,
        
        'database_training_sv_standard': database_training_sv_standard,
        'database_validation_sv_standard': database_validation_sv_standard,
        'database_test_sv_standard': database_test_sv_standard,
        
        'database_scaler': database_scaler,
    }
    pickle.dump(save, f, pickle.HIGHEST_PROTOCOL)

In [54]:
with open(database_dir,'rb') as f: 
    db = pickle.load(f)
    
database_training = db['database_training']
database_validation = db['database_validation']
database_test = db['database_test']

database_training_sv = db['database_training_sv']
database_validation_sv = db['database_validation_sv']
database_test_sv = db['database_test_sv']

database_training_sv_standard = db['database_training_sv_standard']
database_validation_sv_standard = db['database_validation_sv_standard']
database_test_sv_standard = db['database_test_sv_standard']

database_scaler = db['database_scaler']

In [55]:
adf

NameError: name 'adf' is not defined

# Models

Loss function: MSE. To determine a to determine a good choise for the hyperparameter, a grid search is done for some of the models.

List of all models I will use:

In [ ]:
models = []

For models that are in the sklearn framework with the `fit` and `predict` methods, I use this function to perform the evaulation:

In [ ]:
def forecast(model, df_training, df_prediction):
   
    X_train = df_training.iloc[:,1:].values
    y_train = df_training.iloc[:,0].values
    
    X_test = df_prediction.iloc[:,1:].values
    # y_test = df_prediction.iloc[:,0].values
    
    model.fit(X_train, y_train)
    
    y_predicted = model.predict(X_test)
  
    result = pd.Series(data=y_predicted, index = df_prediction.index)
    
    return result

In [ ]:
country = 'France'

df_training = database_training[country]
df_validation = database_validation[country]
df_test = database_test[country]

df_training_sv = database_training_sv[country]
df_validation_sv = database_validation_sv[country]
df_test_sv = database_test_sv[country]


t_forecast_test = df_test_sv.index.values

start_forecast = df_validation_sv.index.values[0]
t_forecast_validation = df_validation_sv.index.values

In [ ]:
#Check forecasting for supervised learning in the evaliation. values from 2011 forecast value for 2012 

print(start_forecast)
print(t_forecast_validation)
print(t_forecast_test)

In [ ]:
df_training_sv

In [ ]:
df_validation_sv

In [ ]:
df_test_sv

## WOE

In [ ]:
name = 'WOE'
y_forecast = get_predictions_weo(df_weo, country = country,
                                 start_forecast =  t_forecast_validation[0],
                                 end_forecast = t_forecast_validation[-1])
mse = mean_squared_error(y_forecast, df_validation_sv['y'].values)
models.append( (name, y_forecast, mse))

## OLS

The ordinary least squares regression is the most famous and basic model in econometrics. The depentend variable is shown as:

\begin{equation}
y = x_1\beta_1 + x_2\beta_2 + ... x_N\beta_N + \beta_{N+1}
\end{equation}

In [ ]:
name = 'OLS'
model = LinearRegression()
y_forecast = forecast(model, df_training_sv, df_validation_sv)
y_forecast = y_forecast.values
mse = mean_squared_error(y_forecast, df_validation_sv['y'].values)
models.append( (name, y_forecast, mse))

## ARIMA

The autoregressive integrated moving average ARIMA($p$, $d$, $q$) model is used in time series analysis.

\begin{equation}
X_t - \alpha_1X_{t-1} - ... - \alpha_pX_{t-p} =  \epsilon_t + \theta_1\epsilon_{t-1} + ... + \theta_q\epsilon_{t-q}
\end{equation}

Here $\alpha _{i}$ are the parameters of the autoregressive part of the model, $\theta _{i}$ are the parameters of the moving average part, $d$ is the degree of differencing and $\epsilon _{t}$ are error terms. There is an implementaion in python in the pmdarima package, which automatically discovers the optimal order for an ARIMA model with exogenous variables.

In [ ]:
name = 'ARIMA'

y_train = df_training_sv.iloc[:, 0]
X_train = df_training_sv.iloc[:, 1:]
y_validation = df_validation_sv.iloc[:, 0]
X_validation = df_validation_sv.iloc[:, 1:]

model = auto_arima(y = y_train,
                   trace=True, 
                   start_p=0,
                   max_p=3,
                   start_q=0,
                   max_q=3,
                   seasonal = False,
                   stepwise= True,
                   exogenous=X_train) 

model.fit(y= y_train, exogenous=X_train)

y_forecast = model.predict(n_periods=y_validation.shape[0],
                      exogenous = X_validation)
mse = mean_squared_error(y_forecast, y_validation)
models.append( (name, y_forecast, mse))

## Elastic Net

In [ ]:

parameters = {'alpha': [0.1, 0.25, 1.0, 2.0, 4.0, 8.0, 16, 32, 128]}
model = Lasso()

clf = GridSearchCV(model, parameters)

X_train = df_training_sv.iloc[:,1:].values
y_train = df_training_sv.iloc[:,0].values


clf.fit(X_train, y_train)

print(clf.best_params_)

In [ ]:
name = 'LASSO'
model = Lasso(alpha = 0.25)
y_forecast = forecast(model, df_training_sv, df_validation_sv)
y_forecast = y_forecast.values
mse = mean_squared_error(y_forecast, df_validation_sv['y'].values)
models.append( (name, y_forecast, mse))

## Support Vector Regression

https://towardsdatascience.com/an-introduction-to-support-vector-regression-svr-a3ebc1672c2
https://scikit-learn.org/stable/modules/generated/sklearn.svm.SVR.html

In [ ]:
parameters = {'kernel': ['linear', 'poly', 'rbf', 'sigmoid'],
    'C': [0.1, 0.25, 1.0, 2.0, 4.0, 8.0],
             'epsilon': [0.01, 0.05, 0.1, 0.25, 0.5]}
model = SVR()
clf = GridSearchCV(model, parameters)

X_train = df_training_sv.iloc[:,1:].values
y_train = df_training_sv.iloc[:,0].values


clf.fit(X_train, y_train)

print(clf.best_params_)

In [ ]:
name = 'SVR'
model = SVR(C=0.1, epsilon=0.05, kernel = 'sigmoid')
y_forecast = forecast(model, df_training_sv, df_validation_sv)
y_forecast = y_forecast.values
mse = mean_squared_error(y_forecast, df_validation_sv['y'].values)
models.append( (name, y_forecast, mse))

## Regression Tree

In [ ]:
parameters = {'max_depth': [2,3,4,5,10],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 5, 10],
     'min_impurity_decrease': [0, 0.0001, 0.001, 0.01, 0.01] }
model = DecisionTreeRegressor()
clf = GridSearchCV(model, parameters)

X_train = df_training_sv.iloc[:,1:].values
y_train = df_training_sv.iloc[:,0].values


clf.fit(X_train, y_train)

print(clf.best_params_)

In [ ]:
name = 'Tree'
model = DecisionTreeRegressor(max_depth = 2,
                              min_impurity_decrease =  0.01, 
                              min_samples_leaf = 2,
                              min_samples_split =  10)
y_forecast = forecast(model, df_training_sv, df_validation_sv)
y_forecast = y_forecast.values
mse = mean_squared_error(y_forecast, df_validation_sv['y'].values)
models.append( (name, y_forecast, mse))

## GBM

In [ ]:
parameters = {'n_estimators':[5, 10, 20, 50, 100], 
              'max_depth':[1, 2, 4],
             'learning_rate': [0.01, 0.03, 0.1, 0.25],
             'min_samples_split':[2, 10]}
model = GradientBoostingRegressor()
clf = GridSearchCV(model, parameters)

X_train = df_training_sv.iloc[:,1:].values
y_train = df_training_sv.iloc[:,0].values


clf.fit(X_train, y_train)

In [ ]:
print(clf.best_params_)

In [ ]:
name = 'GBM'
model = GradientBoostingRegressor(n_estimators = 5, max_depth = 4, 
                                  min_samples_split=2, learning_rate = 0.03)
y_forecast = forecast(model, df_training_sv, df_validation_sv)
y_forecast = y_forecast.values
mse = mean_squared_error(y_forecast, df_validation_sv['y'].values)
models.append( (name, y_forecast, mse))

## RNN

see Notebook 02.

## Reinforcement Learning

see Notebook 03 and 04.

# Evaluation

In [ ]:
df = database_training[country].append(database_validation[country]).append(database_test[country])

fig, ax = plt.subplots()

ax.plot(df['y'], label='real')

for model in models:
    name = model[0]
    y_forecast = model[1]
    mse = model[2]
    
    label = name + ' ' + str(round(mse,3))
    
    ax.plot(t_forecast_validation,  y_forecast, label=label, alpha=0.5)

ax.axvline(x=start_forecast, ymin=0, ymax=1, color='black',linestyle='--', alpha=0.5)

ax.set_xlabel('year') 
ax.set_ylabel('GDP growth change in %') 
ax.set_title("GDP growth - real vs. forecast")
legend  = ax.legend(bbox_to_anchor=(1.05, 1))
fig.autofmt_xdate()
plt.grid()

wdir= r'C:/Users/hauer/Documents/Repositories/cfds_project'
save_dir = os.path.join(wdir, 'forecast_out_of_time.png')

#plt.savefig(save_dir, dpi = 500, bbox_extra_artists=(legend,), bbox_inches='tight')
#plt.close()

In [ ]:
df_validation_sv

# Running the models

This is the final evaluation, so models will be trained on the training set combined with the test set and the MSE is calculated with the test set. 

## Training on every country on its own

In [ ]:
y_forecast_WEO = {}
y_forecast_ARIMA = {}
y_forecast_OLS = {}
y_forecast_LASSO = {}
y_forecast_SVR = {}
y_forecast_TREE = {}
y_forecast_GBM = {}

df_result_single_countries = pd.DataFrame(columns=['country', 'WEO', 'ARIMA', 'OLS', 'LASSO', 'SVR', 'TREE', 'GBM'])

for country in database_training_sv.keys():

    df_training_sv = database_training_sv[country]
    df_validation_sv = database_validation_sv[country]
    
    df_training_sv = pd.concat([df_training_sv, df_validation_sv])
    
    df_test_sv = database_test_sv[country]
    
    t_forecast_test = df_test_sv.index.values
    start_forecast = df_test_sv.index.values[0]

    
    # WEO
    
    y_forecast = get_predictions_weo(df_weo, country = country,
                                     start_forecast =  t_forecast_test[0],
                                     end_forecast = t_forecast_test[-1])
    mse_WEO = mean_squared_error(y_forecast, df_test_sv['y'].values)
    y_forecast_WEO[country] = y_forecast
    
    # ARIMA
    #ValueError: Could not successfully fit ARIMA to input data. 
    #It is likely your data is non-stationary. Please induce stationarity or try a different range of model order params. 
    #If your data is seasonal, check the period (m) of the data.
    
    try:
    
        y_train = df_training_sv.iloc[:, 0]
        X_train = df_training_sv.iloc[:, 1:]
        y_validation = df_test_sv.iloc[:, 0]
        X_validation = df_test_sv.iloc[:, 1:]

        model = auto_arima(y = y_train,
                           trace=True, 
                           start_p=0,
                           max_p=3,
                           start_q=0,
                           max_q=3,
                           seasonal = False,
                           stepwise= True,
                           exogenous=X_train) 

        model.fit(y= y_train, exogenous=X_train)

        y_forecast = model.predict(n_periods=y_validation.shape[0],
                              exogenous = X_validation)
        y_forecast_ARIMA[country] = y_forecast
        mse_ARIMA = mean_squared_error(y_forecast, y_validation)
        
    except Exception as e:
        mse_ARIMA = -1
        y_forecast_ARIMA[country] = [0 for i in range(len(y_forecast))]
        

    
    # OLS
    
    model = LinearRegression()
    y_forecast = forecast(model, df_training_sv, df_test_sv)
    y_forecast = y_forecast.values
    mse_OLS = mean_squared_error(y_forecast, df_test_sv['y'].values)
    y_forecast_OLS[country] = y_forecast
    
    # LASSO

    model = Lasso(alpha = 0.25)
    y_forecast = forecast(model, df_training_sv, df_test_sv)
    y_forecast = y_forecast.values
    mse_LASSO = mean_squared_error(y_forecast, df_test_sv['y'].values)
    y_forecast_LASSO[country] = y_forecast
    
    
    # SVR
    
    model = SVR(C=0.1, epsilon=0.05, kernel = 'sigmoid')
    y_forecast = forecast(model, df_training_sv, df_test_sv)
    y_forecast = y_forecast.values
    mse_SVR = mean_squared_error(y_forecast, df_test_sv['y'].values)
    y_forecast_SVR[country] = y_forecast
    
    
    # Regression Tree
    
    model = DecisionTreeRegressor(max_depth = 2,
                              min_impurity_decrease =  0.01, 
                              min_samples_leaf = 2,
                              min_samples_split =  10)
    y_forecast = forecast(model, df_training_sv, df_test_sv)
    y_forecast = y_forecast.values
    mse_TREE = mean_squared_error(y_forecast, df_test_sv['y'].values)
    y_forecast_TREE[country] = y_forecast


    
    # GBM
    
    model = GradientBoostingRegressor(n_estimators = 5, max_depth = 2, 
                                      min_samples_split=10, learning_rate = 0.01)
    y_forecast = forecast(model, df_training_sv, df_test_sv)
    y_forecast = y_forecast.values
    mse_GBM = mean_squared_error(y_forecast, df_test_sv['y'].values)
    y_forecast_GBM[country] = y_forecast

    
    
    
    df_result_single_countries = pd.concat([pd.DataFrame([[country ,mse_WEO, mse_ARIMA, mse_OLS, mse_LASSO, mse_SVR, mse_TREE, mse_GBM]],
                                                         columns=df_result_single_countries.columns),
                                            df_result_single_countries],ignore_index=True)

Creating Plots

In [ ]:
for country in database_training_sv.keys():

    df = database_training_sv[country].append(database_validation_sv[country]).append(database_test_sv[country])

    fig, ax = plt.subplots()

    ax.plot(df['y'], label='real')

    row = df_result_single_countries[df_result_single_countries['country'] == country]
    for model in ['WEO', 'ARIMA', 'OLS', 'GBM']:
        name = model

        if model == 'WEO':
            y_forecast = y_forecast_WEO[country]
        elif model == 'ARIMA':
            y_forecast = y_forecast_ARIMA[country]
        elif model == 'SVR':
            y_forecast = y_forecast_SVR[country]
        elif model == 'OLS':
            y_forecast = y_forecast_OLS[country]
        elif model == 'GBM':
            y_forecast = y_forecast_GBM[country]

        mse = row[model].values[0]

        label = name + ' ' + str(round(mse,3))

        ax.plot(t_forecast_test,  y_forecast, label=label, alpha=0.5)

    ax.axvline(x=start_forecast, ymin=0, ymax=1, color='black',linestyle='--', alpha=0.5)

    ax.set_xlabel('year') 
    ax.set_ylabel('GDP growth change in %') 
    ax.set_title("GDP growth - real vs. forecast - " + country)
    legend  = ax.legend(bbox_to_anchor=(1.05, 1))
    fig.autofmt_xdate()
    plt.grid()

    wdir= r'C:/Users/hauer/Documents/Repositories/cfds_project/plots_single_countries'
    save_dir = os.path.join(wdir, country+'.png')

    plt.savefig(save_dir, dpi = 500, bbox_extra_artists=(legend,), bbox_inches='tight')
    plt.close()

Result

In [ ]:
df_result_single_countries

In [ ]:
classic_models = ['WEO', 'OLS', 'ARIMA']
machine_learning_models = [x for x in df_result_single_countries.keys() if x not in ['country', 'WEO', 'OLS', 'ARIMA']]

result_single = []

for i in range(0,len(df_result_single_countries)):
    
    df_current = df_result_single_countries.iloc[i,:]
    
    for classic_model in classic_models:
        for machine_learning_model in machine_learning_models:
            if df_current[classic_model] <  df_current[machine_learning_model]:
                x = 0
            else:
                x = 1
            result_single.append(x)

## Training the whole data set

In [ ]:
df_training_sv_complete = pd.DataFrame()
for country in database_training_sv.keys():
    df_training_sv = database_training_sv[country]
    df_validation_sv = database_validation_sv[country]
    
    df_training_sv = pd.concat([df_training_sv, df_validation_sv])

    df_training_sv_complete = pd.concat([df_training_sv_complete, df_training_sv])

Defining RNN

In [ ]:
class LSTMNet(nn.Module):
    def __init__(self, input_size, seq_len, output_size, hidden_dim, n_layers):
        super(LSTMNet, self).__init__()

        self.hidden_dim = hidden_dim
        self.seq_len = seq_len
               
        
        self.lstm1 = nn.LSTM(input_size, hidden_dim)
        self.lstm2 = nn.LSTM(hidden_dim, hidden_dim)
        self.fc = nn.Linear(hidden_dim, output_size)

    def forward(self, x, hidden_1, state_1, hidden_2, state_2):
        r_out, (hidden_out, state_out) = self.lstm1(x, (hidden_1, state_1))      
        r_out, (hidden_out, state_out) = self.lstm2(r_out, (hidden_2, state_2))
        r_out = self.fc(r_out)
        
        return r_out
        
    def initHidden(self):
        return zeros(1, self.seq_len, self.hidden_dim)

In [ ]:
y_forecast_WEO = {}
y_forecast_OLS = {}
y_forecast_LASSO = {}
y_forecast_SVR = {}
y_forecast_TREE = {}
y_forecast_GBM = {}
y_forecast_RNN = {}

df_result_all_countries = pd.DataFrame(columns=['country', 'WEO', 'OLS', 'LASSO', 'SVR', 'TREE', 'GBM', 'RNN'])
N, dummy_dim = database_training_sv_standard['Germany'].shape
dummy_dim -= 1


for country in database_training_sv.keys():
#for country in ['Germany', 'France']:

    
    df_test_sv = database_test_sv[country]
    
    t_forecast_test = df_test_sv.index.values
    start_forecast = df_test_sv.index.values[0]

    
    # WEO
    
    y_forecast = get_predictions_weo(df_weo, country = country,
                                     start_forecast =  t_forecast_test[0],
                                     end_forecast = t_forecast_test[-1])
    mse_WEO = mean_squared_error(y_forecast, df_test_sv['y'].values)
    y_forecast_WEO[country] = y_forecast
    
     

    
    # OLS
    
    model = LinearRegression()
    y_forecast = forecast(model, df_training_sv_complete, df_test_sv)
    y_forecast = y_forecast.values
    mse_OLS = mean_squared_error(y_forecast, df_test_sv['y'].values)
    y_forecast_OLS[country] = y_forecast
    
    
     # LASSO

    model = Lasso(alpha = 0.25)
    y_forecast = forecast(model, df_training_sv_complete, df_test_sv)
    y_forecast = y_forecast.values
    mse_LASSO = mean_squared_error(y_forecast, df_test_sv['y'].values)
    y_forecast_LASSO[country] = y_forecast
    
    
    # SVR
    
    model = SVR(C=0.1, epsilon=0.05, kernel = 'sigmoid')
    y_forecast = forecast(model, df_training_sv_complete, df_test_sv)
    y_forecast = y_forecast.values
    mse_SVR = mean_squared_error(y_forecast, df_test_sv['y'].values)
    y_forecast_SVR[country] = y_forecast
    
    
    # Regression Tree
    
    model = DecisionTreeRegressor(max_depth = 2,
                              min_impurity_decrease =  0.01, 
                              min_samples_leaf = 2,
                              min_samples_split =  10)
    y_forecast = forecast(model, df_training_sv_complete, df_test_sv)
    y_forecast = y_forecast.values
    mse_TREE = mean_squared_error(y_forecast, df_test_sv['y'].values)
    y_forecast_TREE[country] = y_forecast

    
    # GBM
    
    name = 'GBM'
    model = GradientBoostingRegressor(n_estimators = 5, max_depth = 2, 
                                      min_samples_split=10, learning_rate = 0.01)
    y_forecast = forecast(model, df_training_sv_complete, df_test_sv)
    y_forecast = y_forecast.values
    mse_GBM = mean_squared_error(y_forecast, df_test_sv['y'].values)
    y_forecast_GBM[country] = y_forecast
    
    
    # RNN
    
    wdir= r'C:/Users/hauer/Documents/Repositories/cfds_project'
    save_dir = os.path.join(wdir, 'pytorch_models')
    model_name = 'rnn.torch'
    
    hidden_dim = 64
    model = LSTMNet(input_size=6, seq_len=17, output_size=1, hidden_dim=hidden_dim, n_layers=1)
    model.load_state_dict(load( os.path.join(save_dir, model_name)))
    
    
    df = database_training_sv_standard[country].append(database_validation_sv_standard[country]).append(database_test_sv_standard[country])

    n_forecast_validation, _ = database_test_sv_standard[country].shape

    X_eval = df.iloc[:,1:].values
    y_eval = df.iloc[:,0].values
    X_eval_T = from_numpy(X_eval).float()
    N, _ = X_eval_T.shape
    X_eval_T = X_eval_T.view([-1, N, dummy_dim])

    hidden_1 = zeros(1, N, hidden_dim)
    state_1 = zeros(1, N, hidden_dim)

    hidden_2 = zeros(1, N, hidden_dim)
    state_2 = zeros(1, N, hidden_dim)

    model.eval()
    with no_grad():
        y_hat = model(X_eval_T, hidden_1, state_1, hidden_2, state_2)

    y_hat =  y_hat.view(-1).numpy()
    y_forecast = y_hat[-n_forecast_validation:]
    
    # Inverse tranformation 
    
    scaler = database_scaler[country]
    df_output = database_test_sv_standard[country]
    df_output.iloc[:,0] = y_forecast
    df_output = pd.DataFrame(scaler.inverse_transform(df_output))
    y_forecast = df_output.iloc[:,0].values
    
    
    mse_RNN = mean_squared_error(y_forecast, df_test_sv['y'].values)
    y_forecast_RNN[country] = y_forecast
    

    
    
    
    df_result_all_countries = pd.concat([pd.DataFrame([[country ,mse_WEO, mse_OLS, mse_LASSO, mse_SVR, mse_TREE, mse_GBM, mse_RNN]],
                                                        columns=df_result_all_countries.columns),
                                         df_result_all_countries],ignore_index=True)

Creating plots

In [ ]:
for country in database_training_sv.keys():

    df = database_training_sv[country].append(database_validation_sv[country]).append(database_test_sv[country])

    fig, ax = plt.subplots()

    ax.plot(df['y'], label='real')

    row = df_result_all_countries[df_result_all_countries['country'] == country]
    for model in ['WEO', 'OLS', 'GBM', 'RNN']:
        name = model

        if model == 'WEO':
            y_forecast = y_forecast_WEO[country]
        elif model == 'RNN':
            y_forecast = y_forecast_RNN[country]
        elif model == 'OLS':
            y_forecast = y_forecast_OLS[country]
        elif model == 'SVR':
            y_forecast = y_forecast_SVR[country]
        elif model == 'GBM':
            y_forecast = y_forecast_GBM[country]

        mse = row[model].values[0]

        label = name + ' ' + str(round(mse,3))

        ax.plot(t_forecast_test,  y_forecast, label=label, alpha=0.5)

    ax.axvline(x=start_forecast, ymin=0, ymax=1, color='black',linestyle='--', alpha=0.5)

    ax.set_xlabel('year') 
    ax.set_ylabel('GDP growth change in %') 
    ax.set_title("GDP growth - real vs. forecast - " + country)
    legend  = ax.legend(bbox_to_anchor=(1.05, 1))
    fig.autofmt_xdate()
    plt.grid()

    wdir= r'C:/Users/hauer/Documents/Repositories/cfds_project/plots_all_countries'
    save_dir = os.path.join(wdir, country+'.png')

    plt.savefig(save_dir, dpi = 500, bbox_extra_artists=(legend,), bbox_inches='tight')
    plt.close()

Result

In [ ]:
df_result_all_countries

In [ ]:
classic_models = ['WEO', 'OLS']
machine_learning_models = [x for x in df_result_all_countries.keys() if x not in ['country', 'WEO', 'OLS', 'ARIMA']]

result_all = []

for i in range(0,len(df_result_all_countries)):
    
    df_current = df_result_all_countries.iloc[i,:]
    
    for classic_model in classic_models:
        for machine_learning_model in machine_learning_models:
            if df_current[classic_model] <  df_current[machine_learning_model]:
                x = 0
            else:
                x = 1
            result_all.append(x)

# Final Analyis for statistical significance

Drawing bootstrap samples

In [ ]:
B = 1000

bootstrap = np.random.choice(result_single, (len(result),B), replace = True)
bootstrap_means_single = np.mean(bootstrap, axis = 1)
approch_single = ['single' for i in range(len(bootstrap_means_single))]

bootstrap = np.random.choice(result_all, (len(result),B), replace = True)
bootstrap_means_all = np.mean(bootstrap, axis = 1)
approch_all = ['all' for i in range(len(bootstrap_means_all))]


bootstrap_means = np.concatenate( (bootstrap_means_all, bootstrap_means_single))
approach = approch_all + approch_single

In [ ]:
df_result = pd.DataFrame({'means': bootstrap_means, 'approach':approach})

ax = sns.boxplot(x='approach', y='means', data=df_result,
                width = 0.5)

ax.axhline(y=0.5, color='red',linestyle='--', alpha=0.75)

plt.title("final test for statistical significance")


wdir= r'C:\Users\hauer\Documents\Repositories\cfds_project\plot_result'
save_dir = os.path.join(wdir, 'result.png')

plt.savefig(save_dir, dpi = 500, bbox_extra_artists=(legend,), bbox_inches='tight')
plt.close()

## Evaluation of the Deep Reinforcement Learning framework

Runnig the model:

In [ ]:
class DeepQNetwork(nn.Module):
    def __init__(self, lr, input_dims, fc1_dims, fc2_dims, 
            n_actions):
        super(DeepQNetwork, self).__init__()
        self.input_dims = input_dims
        self.fc1_dims = fc1_dims
        self.fc2_dims = fc2_dims
        self.n_actions = n_actions
        self.fc1 = nn.Linear(*self.input_dims, self.fc1_dims)
        self.fc2 = nn.Linear(self.fc1_dims, self.fc2_dims)
        self.fc3 = nn.Linear(self.fc2_dims, self.n_actions)

        self.optimizer = Adam(self.parameters(), lr=lr)
        self.loss = nn.MSELoss()
        self.device = T.device('cuda:0' if T.cuda.is_available() else 'cpu')
        self.to(self.device)

    def forward(self, state):
        x = F.relu(self.fc1(state))
        x = F.relu(self.fc2(x))
        actions = self.fc3(x)

        return actions


class Agent():
    def __init__(self, gamma, epsilon, lr, input_dims, batch_size, n_actions,
            max_mem_size=100000, eps_end=0.05, eps_dec=5e-4):
        self.gamma = gamma
        self.epsilon = epsilon
        self.eps_min = eps_end
        self.eps_dec = eps_dec
        self.lr = lr
        self.action_space = [i for i in range(n_actions)]
        self.mem_size = max_mem_size
        self.batch_size = batch_size
        self.mem_cntr = 0
        self.iter_cntr = 0
        self.replace_target = 100

        self.Q_eval = DeepQNetwork(lr, n_actions=n_actions, input_dims=input_dims,
                                    fc1_dims=64, fc2_dims=32)

        self.state_memory = np.zeros((self.mem_size, *input_dims), dtype=np.float32)
        self.new_state_memory = np.zeros((self.mem_size, *input_dims), dtype=np.float32)
        self.action_memory = np.zeros(self.mem_size, dtype=np.int32)
        self.reward_memory = np.zeros(self.mem_size, dtype=np.float32)
        self.terminal_memory = np.zeros(self.mem_size, dtype=np.bool)

    def store_transition(self, state, action, reward, state_, terminal):
        index = self.mem_cntr % self.mem_size
        self.state_memory[index] = state
        self.new_state_memory[index] = state_
        self.reward_memory[index] = reward
        self.action_memory[index] = action
        self.terminal_memory[index] = terminal

        self.mem_cntr += 1
        
    def get_q_valid(self, q, valid_actions):
        q_valid = [np.nan] * len(q)
        for action in valid_actions:
            q_valid[action] = q[action]
        
        return q_valid

    def choose_action(self, observation, valid_actions):
        if np.random.random() > self.epsilon:
            state = T.tensor([observation], dtype=T.float32).to(self.Q_eval.device)
            q = self.Q_eval.forward(state)
            q = q.detach().numpy().squeeze()
            q = self.get_q_valid(q, valid_actions)
            action = np.nanargmax(q)
        else:
            action = np.random.choice(valid_actions)

        return action

    def learn(self):
        if self.mem_cntr < self.batch_size:
            return

        self.Q_eval.optimizer.zero_grad()

        max_mem = min(self.mem_cntr, self.mem_size)

        batch = np.random.choice(max_mem, self.batch_size, replace=False)

        batch_index = np.arange(self.batch_size, dtype=np.int32)

        state_batch = T.tensor(self.state_memory[batch]).to(self.Q_eval.device)
        new_state_batch = T.tensor(self.new_state_memory[batch]).to(self.Q_eval.device)
        action_batch = self.action_memory[batch]
        reward_batch = T.tensor(self.reward_memory[batch]).to(self.Q_eval.device)
        terminal_batch = T.tensor(self.terminal_memory[batch]).to(self.Q_eval.device)

        q_eval = self.Q_eval.forward(state_batch)[batch_index, action_batch]
        q_next = self.Q_eval.forward(new_state_batch)
        q_next[terminal_batch] = 0.0

        q_target = reward_batch + self.gamma*T.max(q_next,dim=1)[0]

        loss = self.Q_eval.loss(q_target, q_eval).to(self.Q_eval.device)
        loss.backward()
        self.Q_eval.optimizer.step()

        self.iter_cntr += 1
        self.epsilon = self.epsilon - self.eps_dec if self.epsilon > self.eps_min \
                       else self.eps_min

def get_prediction(action, empty_status):
    # Determines prediction on a given empty_status and action
    # if empty, i. e. no stock is in depot, if action == 1 (buying) you bet on rising price
    # if not empty, i. e. stock is in depot, if action == 0 (selling) you bet on falling price
    
    if empty_status:
        if action == 1:
            return 1
        return -1
    else:
        if action == 0:
            return -1
        return 1

class Environment():
    
    
    def __init__(self, n_epochs, window_size_observation, size_time_series, database):
        self.name = 'gao'
        self.n_epochs = n_epochs
        self.window_size_observation = window_size_observation 
        self.size_time_series = size_time_series
        self.current_game = 0
        self.t_current = 0
        self.empty = True
        self.open_cost = 0
        self.database = database
        
        self.list_of_games = self.get_list_of_games()
        self.n_games = len(self.list_of_games)
        self.t_max = self.size_time_series - self.window_size_observation - 1

      
    def get_status_emtpy(self):
        return self.empty

    
    def get_current_df(self):
        return self.list_of_games[self.current_game]

        
    def get_list_of_games(self):
        list_of_games = []
        
        for i in range(self.n_epochs):
            for country in self.database.keys():
                list_of_games.append(self.database[country])
                   
        return list_of_games
    
    
    def reset(self):
        if self.current_game == self.n_games - 1:
            self.current_game = 0
        else:
            self.current_game += 1
            
        self.t_current = 0
        
        observation = self.get_observation()
        
        return observation
        
    
    def step(self, action):
        
        done = False
        if action == 0:		# wait/close
            reward = 0.
            self.empty = True
        elif action == 1:	# open
            reward = self.get_reward_noncash()
            self.empty = False
        elif action == 2:	# keep
            reward = self.get_reward_noncash()
        else:
            raise ValueError('no valid action: ' + str(action))
        
        self.t_current += 1
        #return self.get_state(), reward, self.t == self.t_max, self.get_valid_actions()
        
        
        done = self.t_current == self.t_max
        observation = self.get_observation()
        info = self.get_valid_actions()
        
        return observation, reward, done, info
 
    
    def get_reward_noncash(self):
        df_current = self.list_of_games[self.current_game]
               
        t_1 = self.t_current + self.window_size_observation + 1
        t = self.t_current + self.window_size_observation 

        price_t_1 = df_current.iloc[t_1, 0]
        price_t = df_current.iloc[t, 0]
        
        reward = price_t_1 - price_t
        
        if self.empty:
            reward -= self.open_cost
        
        return reward 
       
    
    
    def get_observation(self):
        df_current = self.list_of_games[self.current_game]
        
        observation = df_current.iloc[self.t_current:(self.t_current + self.window_size_observation), :]
        
        return observation
    
    
    def get_valid_actions(self):
        if self.empty:
            return [0, 1]	# wait, open
        else:
            return [0, 2]	# close, keep 
        
    def set_list_of_games(self, df):
        self.list_of_games = [df]
        self.n_games = 1
  
        
    def render(self):
        pass

Prepare final training database, i. e. the database that consits of the original training and validation set:

In [ ]:
database_training_RL = {}

for country in database_training_sv_standard.keys():
    df_to_add = database_training_sv_standard[country].append(database_validation_sv_standard[country])
    df_to_add = df_to_add.reset_index()
    del df_to_add['index']

    database_training_RL[country] = df_to_add

In [ ]:
N, p = database_training_sv_standard['Germany'].shape


n_epochs = 1
window_size_observation = 15
size_time_series = N


agent = Agent(gamma=0.8, epsilon=1, batch_size=64, n_actions=3, eps_end=0.01, 
              input_dims=[window_size_observation * p], lr=0.001, eps_dec=2e-5)

env = Environment(n_epochs, window_size_observation, size_time_series, database_training_RL)
n_games = env.n_games

n_countries = len(database_training_sv_standard.keys())

scores, eps_history = [], []

for i in range(n_games):
    score = 0
    done = False

    observation = env.reset()
    valid_actions = [0, 1]

    # take only signal as observation for now: 
    #observation = observation.iloc[:, 1:].values.squeeze()
    observation= np.squeeze(observation.values.transpose().reshape((1, -1)))

    while not done:
        action = agent.choose_action(observation, valid_actions)
        observation_, reward, done, valid_actions = env.step(action)


        # take only signal as observation for now: 
        #observation_ = observation_.iloc[:, 1:].values.squeeze()
        observation_= np.squeeze(observation_.values.transpose().reshape((1, -1)))

        score += reward
        agent.store_transition(observation, action, reward, 
                                observation_, done)
        agent.learn()
        observation = observation_

    scores.append(score)
    eps_history.append(agent.epsilon)

    avg_score = np.mean(scores[-100:])
    
    if i % n_countries == 0:
        print('episode ', i / n_countries, 'score %.2f' % score,
                'average score %.2f' % avg_score,
                'epsilon %.2f' % agent.epsilon)

In [ ]:
y_forecast_GAO = {}


for country in database_training_sv_standard.keys():

    df_to_predict = database_training_sv_standard[country].append(database_validation_sv_standard[country]).append(database_test_sv_standard[country])
    df_to_predict = df_to_predict.reset_index()
    del df_to_predict['index']
    n_forecast_validation = 6

    N, p = df_to_predict.shape
    size_time_series = N

    env = Environment(n_epochs, window_size_observation, size_time_series, database_training_sv_standard)

    env.set_list_of_games(df_to_predict)



    agent.epsilon = 0

    actions, empty_status, rewards = [], [], []

    for i in range(1):
        score = 0
        done = False

        observation = env.reset()
        valid_actions = [0, 1]

        # take only signal as observation for now: 
        observation= np.squeeze(observation.values.transpose().reshape((1, -1)))

        while not done:
            action = agent.choose_action(observation, valid_actions)
            observation_, reward, done, valid_actions = env.step(action)


            # take only signal as observation for now: 
            observation_= np.squeeze(observation_.values.transpose().reshape((1, -1)))

            score += reward
            observation = observation_


            empty_status.append(env.get_status_emtpy())
            actions.append(action)
            rewards.append(reward)



        df = env.get_current_df()
        predictions = [get_prediction(action, empty_status) for action, empty in zip(actions, empty_status)]

        predictions = [0 for i in range(window_size_observation)] + predictions
        rewards = [0 for i in range(window_size_observation)] + rewards
        actions = [0 for i in range(window_size_observation)] + actions


    y_forecast = predictions[-n_forecast_validation:]
    y_forecast_GAO[country] = y_forecast


    fig, (ax, ax2) = plt.subplots(2, 1, sharex=True)


    ax.plot(df.iloc[:,0], label='price')
    ax.axvline(x= len(df) - n_forecast_validation - 1, ymin=-100, ymax=500, color='black',linestyle='--', alpha=1)
    ax.grid()
    ax.set_ylabel('price') 
    ax.set_title("Price and predictions")



    ax2.plot(predictions, 'ro-')
    ax2.set_xlabel('t') 
    ax2.set_ylabel('predictions') 



    plt.grid()



    wdir= r'C:/Users/hauer/Documents/Repositories/cfds_project/plots_drl_gao'
    save_dir = os.path.join(wdir, country+'.png')

    plt.savefig(save_dir, dpi = 500, bbox_inches='tight')
    plt.close()

Mapping the prediction from the models, that where trained with the complete data:

In [ ]:
y_forecast_WEO_RL = {}
y_forecast_OLS_RL = {}
y_forecast_GBM_RL = {}
y_forecast_RNN_RL = {}


for country in y_forecast_WEO.keys():
    y_forecast_WEO_RL[country] = np.where(y_forecast_WEO[country].values > 0, 1, -1)
    y_forecast_OLS_RL[country]  = np.where(y_forecast_OLS[country] > 0, 1, -1)
    y_forecast_GBM_RL[country]  = np.where(y_forecast_GBM[country] > 0, 1, -1)
    y_forecast_RNN_RL[country]  = np.where(y_forecast_RNN[country] > 0, 1, -1)

In [ ]:
df_result_RL = pd.DataFrame(columns=['country', 'WEO', 'OLS', 'GBM', 'RNN', 'GAO'])

for country in y_forecast_OLS_RL.keys():
    
    df_test_sv = database_test_sv[country]
    y_real = df_test_sv['y'].values
    y_real = np.where(y_real > 0, 1, -1)
   
   
    mse_WEO = sum(y_real == y_forecast_WEO_RL[country]) / 6
    mse_OLS = sum(y_real == y_forecast_OLS_RL[country]) / 6
    mse_GBM = sum(y_real == y_forecast_GBM_RL[country]) / 6
    mse_RNN = sum(y_real == y_forecast_RNN_RL[country]) / 6
    mse_GAO = sum(y_real == y_forecast_GAO[country]) / 6


    df_result_RL = pd.concat([pd.DataFrame([[country ,mse_WEO,mse_OLS,mse_GBM, mse_RNN, mse_GAO]],
                                                          columns=df_result_RL.columns),
                                             df_result_RL],ignore_index=True)

In [ ]:
df_result_RL